-- The formula list and the manufacturer list, shipped with the software.
--
-- These were being inserted by the demo seed, which meant they existed on
-- whichever machine had run it and nowhere else. A pharmacist on a fresh
-- install opened the medicine form and found an empty formula dropdown.
--
-- They are not demo data. A generic drug name is a generic drug name in every
-- hospital, and the same is true of the manufacturers operating in Pakistan.
-- They belong with the software, the same way a unit name or a tax rate does,
-- so every database gets them exactly once.
--
-- Safe on a database that already has them: a name that exists is left alone,
-- including one a pharmacy has renamed to suit itself.
--
-- ONE TRANSACTION PER FILE.

INSERT INTO salts (name) VALUES
  ('A.T.S Inj'),
  ('Acarbose'),
  ('Acefylline'),
  ('Acetaminophen'),
  ('Acetazolamide'),
  ('Acetylcysteine'),
  ('Acetylparaminophenol'),
  ('Acetylsalicylic Acid'),
  ('Aciclovir'),
  ('Acipimox'),
  ('Acitretin'),
  ('Acriflavine'),
  ('Acyclovir'),
  ('Adapalene'),
  ('Adefovir Dipivoxil'),
  ('Agnus Castus,Utrica Urens,Fenugreek Seeds,Fennel S'),
  ('Albendazole'),
  ('Albumin,Human'),
  ('Alendronate Sodium'),
  ('Alfacalcidol'),
  ('Alfuzosin'),
  ('Aliskiren'),
  ('Allopurinol'),
  ('Almitrine Bismesylate'),
  ('Alphatocopheryl'),
  ('Alprazolam'),
  ('Alprostadil'),
  ('Alverine Citrate'),
  ('Amantadine(Hcl/Sulphate)'),
  ('Ambroxol'),
  ('Amcinonide'),
  ('Amenorrhea'),
  ('Amifostine'),
  ('Amikacin'),
  ('Amiloride'),
  ('Aminohepatone Sulphate'),
  ('Aminophylline'),
  ('Aminoprofen'),
  ('Amiodarone'),
  ('Amipramizide'),
  ('Amitriptyline'),
  ('Amlodipin+Telmisartan'),
  ('Amlodipin+Valsartan'),
  ('Amlodipine 5Mg+Atorvastatin 10Mg'),
  ('Amlodipine Besylate'),
  ('Amlodipine/Valsartan/Hydrochlorothiazide'),
  ('Ammonium Chloride'),
  ('Amodiaquine'),
  ('Amoxicillin'),
  ('Ampicillin'),
  ('Anagrelide'),
  ('Anastrozole'),
  ('Aneurine'),
  ('Antazoline'),
  ('Anti-D (Rho)'),
  ('Anti-Hepatitis Immunoglobulin(Human)'),
  ('Anti-Malaraial Fluorene Mixture'),
  ('Anti-Rabies Immunoglobulin(Human)'),
  ('Anti-Rabies Serum'),
  ('Anti-Rabies Vaccine'),
  ('Anti-Rho Immunglobullin'),
  ('Anti-Snake Venom Serum'),
  ('Anti-Tetanus Immunoglobulin(Human)'),
  ('Antihaemophilic Factors'),
  ('Antipyrine'),
  ('Aprotinin'),
  ('Aripiprazole'),
  ('Artemether'),
  ('Artemether+Lumefantrine'),
  ('Artesunate'),
  ('Ascorbic Acid'),
  ('Asparaginase'),
  ('Aspartame'),
  ('Aspirin'),
  ('Atenolol'),
  ('Atenolol+Chlorthalidone'),
  ('Atomoxetine'),
  ('Atorvastatin'),
  ('Atorvastatin+Ezetimibe'),
  ('Atracurium Besylate'),
  ('Atropine & Salts'),
  ('Attapulgite'),
  ('Azathioprine'),
  ('Azelaic Acid'),
  ('Azelastine Hcl'),
  ('Azidamfenicol'),
  ('Azithromycin'),
  ('B.C.G. Vaccine'),
  ('Bacampicillin'),
  ('Bacitracin & Salts'),
  ('Balance Electrolyte'),
  ('Balance Salt'),
  ('Bambuterol'),
  ('Bamifylline'),
  ('Basiliximab'),
  ('Beclomethasone Dipropionate'),
  ('Bemetanide And Slow Potassium'),
  ('Benzalkonium Chloride'),
  ('Benzathine Penicillin'),
  ('Benzhexol'),
  ('Benzocaine'),
  ('Benzoyl Metronidazole'),
  ('Benzoyl Peroxide'),
  ('Benzydamine'),
  ('Benzyl Benzoate'),
  ('Benzyl Penicillin & Salt'),
  ('Beractant'),
  ('Betahistine'),
  ('Betahistine Dihydrochloride'),
  ('Betaine Glucourinate'),
  ('Betamethasone & Salt'),
  ('Betamethasone Dipropionate'),
  ('Betaxolol Hcl'),
  ('Bevacizumab'),
  ('Bezafibrate'),
  ('Bicalutamide'),
  ('Bifonazole'),
  ('Bimatoprost'),
  ('Bisacodyl'),
  ('Bismuth Subcitrate'),
  ('Bismuth Subnitrate'),
  ('Bismuth Subsalicylate'),
  ('Bisoprolol'),
  ('Bisoprolol Fumarate'),
  ('Bisoprolol Fumarate&Hydrochlorothiazide'),
  ('Bistropamide'),
  ('Black Haw,Chamaelirium,Alertis Farinosa,Vit C'),
  ('Bleomycin'),
  ('Boric Acid'),
  ('Brimonidine Tartrate'),
  ('Brinzolomide'),
  ('Bromazepam'),
  ('Bromelain'),
  ('Bromelain+Trypsin'),
  ('Bromhexine'),
  ('Bromocriptine'),
  ('Buclizine'),
  ('Budesonid'),
  ('Bufexamac'),
  ('Buflomedil Hcl'),
  ('Bumetanide'),
  ('Bupivacaine'),
  ('Buprenorphine'),
  ('Bupropion Hcl'),
  ('Buspirone Hcl'),
  ('Butoconazole'),
  ('Butoxyphenol Acetahydroxymic Acid'),
  ('Caffeine'),
  ('Calamine'),
  ('Calciferol'),
  ('Calcipotriol'),
  ('Calcitriol'),
  ('Calcium Carbonate'),
  ('Calcium Chloride'),
  ('Calcium Dobesilate'),
  ('Calcium Folinate'),
  ('Calcium Galactogluconate'),
  ('Calcium Glucono Galacto Gluconate'),
  ('Calcium Hypochloride'),
  ('Calcium Lactate'),
  ('Calcium Leucovorin'),
  ('Calcium Pantothenate'),
  ('Calcium Phosphate'),
  ('Calcium Salts+Amino Acids'),
  ('Calcium Supplement'),
  ('Calcium+Vitamin C3'),
  ('Calcium+Vitamin D3'),
  ('Candesartan'),
  ('Candesartan Cilexetil'),
  ('Candesartan Cilexetil+Hydrochlorothiazide'),
  ('Capecitabine'),
  ('Captodiamine'),
  ('Captopril'),
  ('Carbachol'),
  ('Carbamazepine'),
  ('Carbamide Peroxide'),
  ('Carbidopa'),
  ('Carbimazole'),
  ('Carbocisteine'),
  ('Carboplatin'),
  ('Carminative Mixture'),
  ('Carvedilol'),
  ('Cefaclor'),
  ('Cefadroxil'),
  ('Cefadroxil Monohydrate'),
  ('Cefatrizine'),
  ('Cefazoline'),
  ('Cefdinir'),
  ('Cefepime'),
  ('Cefixime'),
  ('Cefoperazone Sodium'),
  ('Ceforanide'),
  ('Cefotaxime Sodium'),
  ('Cefpirome'),
  ('Cefpodoxime'),
  ('Cefprozil'),
  ('Ceftazidime'),
  ('Ceftibuten'),
  ('Ceftizoxime'),
  ('Ceftriaxone'),
  ('Cefuroxime'),
  ('Celecoxib'),
  ('Cephalexin'),
  ('Cephazoline'),
  ('Cephradine'),
  ('Cetalkonium Chloride'),
  ('Cetirizine'),
  ('Cetrimide'),
  ('Cetylpyridinium Chloride'),
  ('Chloral Hydrate'),
  ('Chloramphenicol'),
  ('Chlordiazepoxide'),
  ('Chlorhexidine & Salts'),
  ('Chlorobutanol'),
  ('Chlorobutol'),
  ('Chloroquine Phosphate'),
  ('Chloroxylenol'),
  ('Chlorpheniramine Maleate'),
  ('Chlorpromazine'),
  ('Chlorpropamide'),
  ('Chlorprophenpyridamine Maleate'),
  ('Chlorquinaldol'),
  ('Chlorthalidone'),
  ('Cholecalciferol'),
  ('Choline Alfoserate'),
  ('Choline Salicylate'),
  ('Chondroitin Sulphate'),
  ('Chorionic Gonadoptrophin'),
  ('Chymotrypsin'),
  ('Ciclopiroxolamine'),
  ('Cilastatin'),
  ('Cilazapril'),
  ('Cilostazol'),
  ('Cimetidine'),
  ('Cinchocaine'),
  ('Cinitapride'),
  ('Cinnarizine'),
  ('Ciprofloxacin'),
  ('Ciprofloxacin/Lignocaine'),
  ('Cisplatin'),
  ('Cisplatinum'),
  ('Citalopram'),
  ('Citicoline'),
  ('Citrulline Maleate'),
  ('Clarithromycin'),
  ('Clavulanic Acid'),
  ('Clemastine'),
  ('Clidinium Bromide'),
  ('Clindamycin'),
  ('Clioquinol'),
  ('Clioquinol Hc'),
  ('Clobazam'),
  ('Clobetasol Propionate'),
  ('Clomiphene Citrate'),
  ('Clomipramine'),
  ('Clonazepam'),
  ('Clopidogrel'),
  ('Clopidogrel+Aspirin'),
  ('Clorazepate'),
  ('Clotrimazole'),
  ('Cloxacillin'),
  ('Clozapine'),
  ('Co-Amoxiclav'),
  ('Co-Dergocrine Mesylate'),
  ('Co-Trimoxazole'),
  ('Coal Tar'),
  ('Codeine'),
  ('Colchiecine'),
  ('Conjugated Oestrogens'),
  ('Cortisone'),
  ('Croconazole Hcl'),
  ('Cromoglycate'),
  ('Crotamiton'),
  ('Cyanocobalamin'),
  ('Cyclizine'),
  ('Cyclobenzaprine Hcl'),
  ('Cyclodextrin(Alpha)'),
  ('Cyclonamine'),
  ('Cyclopentolate'),
  ('Cyclophosphamide'),
  ('Cycloserine'),
  ('Cyclosporin'),
  ('Cyproheptadine'),
  ('Cyproterone'),
  ('Cytarabine'),
  ('D-Alpha Tocopherol'),
  ('Dacarbazine'),
  ('Daclizumab'),
  ('Dactinomycin'),
  ('Dalteparin Sodium'),
  ('Danazol'),
  ('Daunomycin'),
  ('Daunorubicin'),
  ('Deferasirox'),
  ('Deferiorone'),
  ('Deferoxamine Mesylate'),
  ('Deltahydrocortisone'),
  ('Dequalinium Chloride'),
  ('Desferrioxamine B Methanesulphonate'),
  ('Desferrioxamine Mesylate'),
  ('Desloratadine'),
  ('Desmopressin'),
  ('Desogestrel'),
  ('Dexamethasone & Salts'),
  ('Dexpanthenol'),
  ('Dextran'),
  ('Dextropropoxyphene'),
  ('Dextrose 10%+Sodium Chloride 0.9%'),
  ('Dextrose 2.5%+Sodium Chloride 0.45%'),
  ('Dextrose 3.3%+Sodium Chloride 0.3%'),
  ('Dextrose 4.3%+Sodium Chloride 0.18%'),
  ('Dextrose 5% Sodium Chloride 0.9%'),
  ('Dextrose 5%+Sodium Chloride 0.45%'),
  ('Dextrose 5%/10%/25%'),
  ('Di-Iodohydroxy Quinoline'),
  ('Diazepam'),
  ('Dibromopropamidineisethionate'),
  ('Dichlorhydroxy Quinoline'),
  ('Diclofenac Potassium'),
  ('Diclofenac Sodium'),
  ('Diclofenac Sodium And Misoprostol'),
  ('Diclofenac Sodium+Misoprostol'),
  ('Dicyclomine'),
  ('Didanosine'),
  ('Diethylamine Salicylate'),
  ('Diflucortolone Valerate'),
  ('Diflucortolone Valerate+Chlorquinaldol'),
  ('Digoxin'),
  ('Dihydroartemisinin/Piperaquine Phosphate'),
  ('Dihydroergocryptine Mesylate'),
  ('Diiodoxyquinoleine'),
  ('Diloxanide'),
  ('Diltiazem'),
  ('Dimenhydrinate'),
  ('Dimethylbiguanide'),
  ('Dimethylcysteine'),
  ('Dimethylpolysiloxane'),
  ('Dimethylsulfoxide'),
  ('Dinoprost'),
  ('Dinoprostone'),
  ('Dioctahedral Smectite'),
  ('Diosmin'),
  ('Diphenhydramine Theoclate'),
  ('Diphenoxylate'),
  ('Diphenoxylate Atropine Sulphate'),
  ('Diphenylhydantoin'),
  ('Diphtheria Antitoxin'),
  ('Diphtheria Pertusis,Tetanus Polio&Hib Vaccine'),
  ('Diphtheria Pertusis,Tetanus Vaccine'),
  ('Diphtheria Pertusis,Tetanus&Hepatitis B Vaccine'),
  ('Diphtheria Pertusis,Tetanus&Hib Vaccine'),
  ('Diphtheria Pertusis,Tetns,Polio,Hib&Hepatis B Vacn'),
  ('Dipivefrin Hcl'),
  ('Diptheria Antitoxin'),
  ('Dipyridamole'),
  ('Disodium Hydrogen Citrate'),
  ('Disopyramide'),
  ('Dithranol'),
  ('Dithranol 0.1% Salicylic Acid 0.5%'),
  ('Divalprex Sodium'),
  ('Dobutamine'),
  ('Docetaxel'),
  ('Docusate'),
  ('Domperidone'),
  ('Domperidone Maleate'),
  ('Domperidone+Cinnarizine'),
  ('Donepezil'),
  ('Dopamine'),
  ('Dorzolamide'),
  ('Dothiepin'),
  ('Doxazosin Mesylate'),
  ('Doxofylline'),
  ('Doxorubicin'),
  ('Doxycycline'),
  ('Dpt Vaccine'),
  ('Dpt+Hepatits B Vaccine'),
  ('Dpt+Hib Vaccine'),
  ('Dpt+Polio+Hib'),
  ('Dpt+Polio+Hib+Hepatits B'),
  ('Drotaverine'),
  ('Dt Vaccine'),
  ('Duloxetine'),
  ('Dutasteride'),
  ('Dybenal'),
  ('Dydrogesterone'),
  ('Ebastine'),
  ('Econazole Nitrate'),
  ('Efavirenz'),
  ('Eletriptan'),
  ('Emedastine'),
  ('Enalapril Maleate'),
  ('Enema'),
  ('Enflurane'),
  ('Enoxacin'),
  ('Enoxaparin'),
  ('Enoximone'),
  ('Entecavir'),
  ('Eperisone Hcl'),
  ('Ephedrine Hcl'),
  ('Epinephrine'),
  ('Epirubicin'),
  ('Epoetin Alpha'),
  ('Epoetin Beta'),
  ('Eprosartan'),
  ('Eptacog Alfa'),
  ('Eptifibatide'),
  ('Erdosteine'),
  ('Ergotamine Tartrate'),
  ('Erlotinib'),
  ('Ertapenem'),
  ('Erythromycin'),
  ('Erythropoietin'),
  ('Escitalopram'),
  ('Escitalopram Oxalate'),
  ('Esdepallethrine'),
  ('Esomeprazole'),
  ('Essential Phospholipids'),
  ('Estazolam'),
  ('Estradiol'),
  ('Etamsylate'),
  ('Ethambutol'),
  ('Ethamsylate'),
  ('Ethinyloestradiol'),
  ('Ethionamide'),
  ('Ethiyloestrenol'),
  ('Ethophenylbarbituric Acid'),
  ('Ethylphenylbarbituric Acid'),
  ('Etifoxine Hcl'),
  ('Etomidate'),
  ('Etoposide'),
  ('Euflavin'),
  ('Everolimus'),
  ('Ezetimibe'),
  ('Factor 7A Recombinant'),
  ('Famciclovir'),
  ('Famotidine'),
  ('Febuxostate'),
  ('Felodipine'),
  ('Fenofibrate'),
  ('Fenoximone'),
  ('Fentanyl'),
  ('Fenticonazole Nitrate'),
  ('Ferrous Fumarate'),
  ('Ferrous Gluconate'),
  ('Ferrous Sulphate'),
  ('Fexofenadine'),
  ('Fexofenadine+Pseudoephedrine'),
  ('Filgrastim'),
  ('Finasteride'),
  ('Flavanoidic Micronize'),
  ('Flavoxate Hcl'),
  ('Flavoxate Hcl And Propyhenazone'),
  ('Floctafenine'),
  ('Fluconazole'),
  ('Flucoxacilline'),
  ('Fludarabine Phosphate'),
  ('Fludiazepam'),
  ('Flumazenil'),
  ('Flumethasone'),
  ('Flunarizine'),
  ('Flunisolide'),
  ('Fluocinolone'),
  ('Fluorescein Sodium'),
  ('Fluorometholone'),
  ('Fluoroprednesolone'),
  ('Fluorouracil'),
  ('Fluoxetine Hcl'),
  ('Flupenthixol'),
  ('Fluphenazine(& Salts)'),
  ('Flurbiprofen'),
  ('Flutamide'),
  ('Fluticasone Propionate'),
  ('Fluvastatin'),
  ('Fluvoxamine Meleate'),
  ('Folic Acid'),
  ('Follitropin Alpha'),
  ('Follitropin Beta'),
  ('Fondaparinux Sodium'),
  ('Formoterol'),
  ('Fosfomycin'),
  ('Fosinopril Sodium'),
  ('Framycetin Sulphate'),
  ('Fructose'),
  ('Frusemide'),
  ('Fsh/Urofollitropin'),
  ('Furazolidone'),
  ('Furosemide'),
  ('Furosemide+Amiloride Hcl'),
  ('Fusidic Acid(& Salts)'),
  ('Gabapentin'),
  ('Gadodiamide'),
  ('Ganciclovir'),
  ('Ganirelix'),
  ('Gas Gangrene Antitoxin'),
  ('Gatifloxacin'),
  ('Gelatin(Succinylated)'),
  ('Gemcitabine'),
  ('Gemfibrozil'),
  ('Gemifloxacin'),
  ('Gemifloxacin Mesylate'),
  ('Gentamicin Sulphate'),
  ('Gentamycin'),
  ('Gentian Violet'),
  ('Gestodene'),
  ('Ginkgo Biloba Extract'),
  ('Ginkgo Biloba,Gingseng,Natural Vit C,Piperine'),
  ('Glibenclamide 1.25Mg+Metformin 250Mg'),
  ('Glibenclamide 2.5Mg'),
  ('Glibenclamide 5Mg+Metformin 500Mg'),
  ('Gliclazide'),
  ('Glimepiride'),
  ('Glimepiride + Metformin'),
  ('Glimepiride+Pioglitazone'),
  ('Glipizide'),
  ('Gliquidone'),
  ('Glucosamine Sulphate'),
  ('Glycerine Suppositories'),
  ('Glyceryl Guacolate'),
  ('Glyceryl Trinitrate'),
  ('Glycine Irrigation Solution'),
  ('Glycolic Acid'),
  ('Glycopyrrolate'),
  ('Glycopyrronium Bromide'),
  ('Goserelin'),
  ('Gramicidin'),
  ('Granisetron'),
  ('Gripe Water'),
  ('Griseofulvin'),
  ('Group Of Enzyms'),
  ('Guaiphenesin'),
  ('Haemodialysis Soln'),
  ('Haemophillus Influenza Type B(Hiv)Vaccine'),
  ('Halofantrine Hcl'),
  ('Halomethasone'),
  ('Haloperidol'),
  ('Hartmann''S Soln'),
  ('Hcg(Human Chorionic Gonadotrophin)'),
  ('Heparin'),
  ('Heparinoid'),
  ('Hepatitis A Vaccine'),
  ('Hepatitis B Immunoglobulin'),
  ('Hepatitis B Vaccine'),
  ('Hespridin'),
  ('Hexahydroadiphenine'),
  ('Hexamine(Methanaminehippurate)'),
  ('Hmg'),
  ('Human Chorionic Gonadotropin'),
  ('Human Prothrombin Complex,Factor Ix'),
  ('Hyaluronic Acid & Salts'),
  ('Hydrochlorothiazide'),
  ('Hydrocortisone'),
  ('Hydrocortisone+Clotrimazol'),
  ('Hydroquinone'),
  ('Hydroxcobalamin'),
  ('Hydroxychloroquine Sulphate'),
  ('Hydroxyethyl Starch'),
  ('Hydroxyprogesterone Caproate'),
  ('Hydroxypropyl Methylcellulose'),
  ('Hydroxyurea'),
  ('Hydroxyzine'),
  ('Hyoscine N-Butylbromide'),
  ('Hyoscyamine(& Salts)'),
  ('Hypromellose'),
  ('Ibandronic Acid'),
  ('Ibuprofen'),
  ('Idarubicin'),
  ('Idoxuridin'),
  ('Ifosfamide'),
  ('Imatinib Mesylate'),
  ('Imidapril'),
  ('Imipenem'),
  ('Imipramine'),
  ('Immune Globulin(Human)Im'),
  ('Immune Globulin(Human)Iv'),
  ('Indapamide'),
  ('Indomethacin'),
  ('Infliximab'),
  ('Influenza Vaccine'),
  ('Inh'),
  ('Insulin Aspart'),
  ('Insulin Aspart+Aspart Protamine'),
  ('Insulin Bovine'),
  ('Insulin Detemir'),
  ('Insulin Glargine'),
  ('Insulin Glulisine'),
  ('Insulin Glulisine/Insulin Glulisine'),
  ('Insulin Human'),
  ('Insulin Lispro'),
  ('Insulin Lispro+Protamine Sulphate'),
  ('Interferon Alpha 2A'),
  ('Interferon Alpha 2B'),
  ('Iodide Salts&Ascorbic Acid'),
  ('Iodine(Sublimed)'),
  ('Iohexol'),
  ('Iopamidol'),
  ('Iopromide'),
  ('Ipratropium Bromide'),
  ('Ipriflavone'),
  ('Irbesartan'),
  ('Irbesartan/Hydrochlorothiazide'),
  ('Irinotecan Hcl Trihydrate'),
  ('Iron & Vitamins With Folic Acid'),
  ('Iron Polymaltose Complex'),
  ('Iron Polymaltose Complex +Folic Acid'),
  ('Iron Proteinsuccinylate+Folic Acid'),
  ('Iron Sorbitol Complex'),
  ('Iron Sucrose'),
  ('Isoconazole Nitrate'),
  ('Isoflurane'),
  ('Isoniazid'),
  ('Isonicotinyl Hydrozide'),
  ('Isopropamide'),
  ('Isopropylantipyrine'),
  ('Isopropylphenazone'),
  ('Isosorbide Dinitrate'),
  ('Isosorbide-5-Mononitrate'),
  ('Isotretinoin'),
  ('Ispaghulla Husk'),
  ('Itopride Hcl'),
  ('Itraconazole'),
  ('Kanamycin'),
  ('Kaolin Pectin'),
  ('Ketamine Hcl'),
  ('Ketoconazole'),
  ('Ketoprofen'),
  ('Ketorolac Tromethamine'),
  ('Ketotifen'),
  ('L-Dopa'),
  ('L-Ornithine L-Aspartate'),
  ('Labetalol'),
  ('Lactic Acid'),
  ('Lactobacillus Acidophilus'),
  ('Lactoserum+Lactic Acid'),
  ('Lactulose'),
  ('Laevulose'),
  ('Lamivudine'),
  ('Lamotrigine'),
  ('Lansoprazole'),
  ('Latanoprost'),
  ('Leflunomide'),
  ('Lenograstim'),
  ('Lercanidipine'),
  ('Letrozole'),
  ('Leucovorin'),
  ('Leuprorelin Acetate'),
  ('Levamisole'),
  ('Levetriacetam'),
  ('Levobunolol Hcl'),
  ('Levocarnitine'),
  ('Levocetrizine'),
  ('Levofloxacin'),
  ('Levonorgestrel'),
  ('Levosulpiride'),
  ('Lidocaine'),
  ('Lignocaine'),
  ('Lincomycin'),
  ('Lindane'),
  ('Linezolid'),
  ('Liquid Paraffin'),
  ('Lisinopril'),
  ('Lisuride'),
  ('Lithium Corbonate'),
  ('Lodoxamide'),
  ('Lomefloxacin'),
  ('Loperamide'),
  ('Lopinavir'),
  ('Loratadine'),
  ('Lorazepam'),
  ('Lormetazepam'),
  ('Losartan Potassium'),
  ('Losartan Potassium & Hydrochlorothiazide'),
  ('Lovastatin'),
  ('Loxoprofen Sodium'),
  ('Lumefantrine'),
  ('Lutein/Zeaxanthin With Multi Vitamin'),
  ('Lynoestrenol'),
  ('Mag.Trisilicate'),
  ('Magaldrate'),
  ('Magnesium Chloride'),
  ('Magnesium Sulphate'),
  ('Mannitol Inj'),
  ('Maprotiline Hcl'),
  ('Measles Vaccine'),
  ('Measles,Mumps,Rubella Vaccine'),
  ('Mebendazole'),
  ('Mebeverine Hcl'),
  ('Mebeverine Hcl+Ispaghula Husk'),
  ('Mebhydrolin'),
  ('Mebuprofen'),
  ('Meclizine'),
  ('Mecobalamine'),
  ('Medazepam'),
  ('Medroxyprogesterone Acetate'),
  ('Mefenamic Acid'),
  ('Mefloquine'),
  ('Megestrol Acetate'),
  ('Meglumine Antimoniate'),
  ('Meglumine Diatrizoate'),
  ('Meglumine Gadopentetate'),
  ('Meladinine'),
  ('Melitracen'),
  ('Meloxicam'),
  ('Melphalan'),
  ('Memantine Hcl'),
  ('Meningitis Vaccine'),
  ('Menotrophin'),
  ('Mepartricin'),
  ('Mepivacaine'),
  ('Meprobamate'),
  ('Mepvramine'),
  ('Mercaptopurine'),
  ('Meropenem'),
  ('Mesalazine'),
  ('Mesna'),
  ('Mesterolone'),
  ('Metacortandralone'),
  ('Metacycline Hcl'),
  ('Metformin Hcl'),
  ('Methamino Diazepoxide'),
  ('Methotrexate'),
  ('Methoxsalen'),
  ('Methylcellulose'),
  ('Methyldopa'),
  ('Methylergometrine Maleate'),
  ('Methylestradiol'),
  ('Methylestrenolone'),
  ('Methylphenidate'),
  ('Methylprednisolone(& Salts)'),
  ('Methyltestosterone'),
  ('Metoclopramide'),
  ('Metoclopramide Resinate'),
  ('Metopine'),
  ('Metoprolol'),
  ('Metronidazole'),
  ('Metronidazole+Diloxanide Fluroate'),
  ('Metronidazole+Diloxanide Furoate'),
  ('Mianserin Hcl'),
  ('Miconazole Nitrate'),
  ('Midazolam'),
  ('Miltefosine'),
  ('Minocycline'),
  ('Mirtazapine'),
  ('Misoprostol'),
  ('Mitomycin'),
  ('Mitoxantrone Hcl'),
  ('Moclobemide'),
  ('Modafinil'),
  ('Mometasone Furoate'),
  ('Montelukast'),
  ('Moxifloxacin'),
  ('Moxifloxacin+Dexamethasone'),
  ('Mulit Vitamin With Ginseng'),
  ('Multivitamins+Mineral+Calcium+Iron'),
  ('Mupirocin'),
  ('Mycophenolate Mofetil'),
  ('N-Acetyl Aspartyl-L-Glutamic Acid'),
  ('Nabumetone'),
  ('Nadroparin Calcium'),
  ('Naftifine'),
  ('Nalbuphine Hcl'),
  ('Nalidixic Acid'),
  ('Naloxone Hcl'),
  ('Nandrolone Decanoate'),
  ('Nandrolone Phenylpropionate'),
  ('Naphazoline(& Salts)'),
  ('Naproxen'),
  ('Naproxen Sodium'),
  ('Natamycin'),
  ('Nateglinide'),
  ('Nefopam'),
  ('Nelfinavir Mesylate'),
  ('Neomycin(& Salts)'),
  ('Neostigmine(& Salts)'),
  ('Netilmicin Sulphate'),
  ('Nevirapine'),
  ('Niaprazine'),
  ('Niclosamide'),
  ('Nicorandil'),
  ('Nicotinic Acid'),
  ('Nifedipine'),
  ('Nifuroxazide'),
  ('Nikethamide'),
  ('Nilotinib'),
  ('Nimesulide'),
  ('Nimetazapam'),
  ('Nimodipine'),
  ('Nitrazepam'),
  ('Nitrofurantoin'),
  ('Nitrofurazone'),
  ('Nitroglycerine Trinitrate'),
  ('Nizatidine'),
  ('Noradrenaline'),
  ('Norepinephrine'),
  ('Norethindrone'),
  ('Norethisterone'),
  ('Norethisterone Acetate'),
  ('Norethisterone Oenanthate'),
  ('Norfloxacin'),
  ('Norgestrel'),
  ('Normethandrone'),
  ('Nortestosteron Decanate'),
  ('Nortestosteron Phenylpropionate'),
  ('Nortriptylline Hcl'),
  ('Nystatin'),
  ('Octreotide Acetate'),
  ('Oestradiol'),
  ('Oestrogens Conjugated(Natural)'),
  ('Ofloxacin'),
  ('Olanzapine'),
  ('Olmesartan Medoxomil'),
  ('Omalizumab'),
  ('Omega-3 Acidethylesters'),
  ('Omeprazole'),
  ('Omeprazole+Metronidazole'),
  ('Ondansetron Hcl'),
  ('Oral Dehydration Salt'),
  ('Orlistat'),
  ('Ornithine Aspartate'),
  ('Orphenadrin Citrate'),
  ('Orphenadrin Citrate Paracetamol'),
  ('Oseltamivir'),
  ('Ossein Mineral Complex Vitamin D'),
  ('Otilonium Bromide'),
  ('Oxaliplatin'),
  ('Oxaprozin'),
  ('Oxatomide'),
  ('Oxazepam'),
  ('Oxcarbazepine'),
  ('Oxcytetracycline'),
  ('Oxethazaine'),
  ('Oxybutynin'),
  ('Oxymetazolin'),
  ('Oxytocin'),
  ('Paclitaxel'),
  ('Pamidronate Disodium'),
  ('Pancuronium Bromide'),
  ('Pantoprazole'),
  ('Pantothenic Acid'),
  ('Paracetamol'),
  ('Paracetamol/Pamabrom'),
  ('Paraffin Liquid'),
  ('Paroxetine'),
  ('Paroxetine Hydrochloride'),
  ('Pectin'),
  ('Pefloxacin'),
  ('Pegaptanib Na'),
  ('Peginterferon Alfa-2A'),
  ('Peginterferon Alfa-2B'),
  ('Pemetrexed'),
  ('Penicillamine'),
  ('Penicillin G'),
  ('Penicillin V'),
  ('Pentazocine (& Salts)'),
  ('Pentothal Sodium'),
  ('Pentoxifyline'),
  ('Perindopril'),
  ('Peritoneal Dialysis Soln'),
  ('Permethol'),
  ('Permethrin'),
  ('Pertussis Vaccine'),
  ('Phenazone'),
  ('Phenazopyridine Hcl'),
  ('Pheniramine Maleate'),
  ('Phenobarbital'),
  ('Phenobarbitone'),
  ('Phenothiazine'),
  ('Phenylbutazone'),
  ('Phenylephrine'),
  ('Phenytoin'),
  ('Phloroglucinol'),
  ('Phloroglucinol Hydrate+Trimethylphloroglucinol'),
  ('Phytomenadione'),
  ('Pilocarpine'),
  ('Pindolol'),
  ('Pioglitazone'),
  ('Pioglitazone+Metformin'),
  ('Pipemidic Acid'),
  ('Piperacillin'),
  ('Piperazine'),
  ('Piperonyl Butoxide'),
  ('Pipethanate Ethobromide'),
  ('Piracetam'),
  ('Pirfenoxone'),
  ('Piribedil'),
  ('Piroxicam'),
  ('Piroxicam-Beta-Cyclodextrin'),
  ('Pizotifen'),
  ('Plasma Protein Fraction,Human'),
  ('Pneumococcal Vaccine'),
  ('Polidocanol'),
  ('Polio Vaccine'),
  ('Polyacrylic Acid'),
  ('Polygeline'),
  ('Polymyxin B Suphate'),
  ('Polypeptide'),
  ('Polysaccharide Iron Complex'),
  ('Polyunasturated Phospholipids(Ppl)'),
  ('Polyvidone'),
  ('Polyvinyl Alcohol'),
  ('Polyvinylpyrrolidone'),
  ('Poractant Alfa'),
  ('Potassium Chloride'),
  ('Potassium Citrate'),
  ('Potassium Iodide'),
  ('Potassium Nitrate'),
  ('Povidone Iodine'),
  ('Pralidoxime Methylsulphate'),
  ('Pramoxine'),
  ('Prasugrel'),
  ('Pravastatin'),
  ('Prazosin'),
  ('Prednicarbate'),
  ('Prednisolone'),
  ('Pregabalin'),
  ('Procaine Hcl'),
  ('Procaine Penicillin G'),
  ('Procaterol Hcl'),
  ('Prochlorperazine'),
  ('Procyclidine'),
  ('Progesterone'),
  ('Progestin'),
  ('Proglumetacin'),
  ('Proglumide'),
  ('Promethazine Hcl'),
  ('Promethazine Theoclate'),
  ('Promethazine+Pholcodine'),
  ('Promethazine+Pholcodine+Ephedrine'),
  ('Proparacaine Hcl'),
  ('Prophenpyridamine'),
  ('Propofol'),
  ('Propranolol Hcl'),
  ('Propylthiouracil'),
  ('Propyphenazone'),
  ('Prostaglandin E1'),
  ('Prostaglandin F2 Alpha'),
  ('Protamine Sulphate'),
  ('Protirelin Tartrate'),
  ('Proxymetacaine'),
  ('Pseudoephedrine'),
  ('Psyllium Husk'),
  ('Pyranisamine'),
  ('Pyrantel Pamoate'),
  ('Pyrazinamide'),
  ('Pyridostigmine Bromide'),
  ('Pyrilamine'),
  ('Pyrimethamine'),
  ('Pyrithioxine'),
  ('Pyritinol Hcl'),
  ('Quetiapine'),
  ('Quetiapine Fumarate'),
  ('Quinapril'),
  ('Quinine Bisulphate'),
  ('Quinine Dihydrochloride'),
  ('Quinine Hcl'),
  ('Rabeprazole'),
  ('Rabies Antiserum'),
  ('Rabies Immunoglobulin'),
  ('Rabies Vaccine'),
  ('Raloxifene'),
  ('Ramipril'),
  ('Ramipril+Hydrochlorothiazide'),
  ('Ranibizumab'),
  ('Ranitidine'),
  ('Raubasine'),
  ('Repaglinide'),
  ('Rerecombinant Human Erythropoietin Alpha'),
  ('Resorcinol'),
  ('Reteplase'),
  ('Rho(D)Immunoglobulin'),
  ('Ribavirin'),
  ('Riboflavin'),
  ('Rifampicin'),
  ('Rifampicin 450Mg&Isoniazid 300Mg'),
  ('Rifampicin+Inh'),
  ('Ringer''S Lactate+5% Dextrose'),
  ('Ringer''S Lactated'),
  ('Ringer''S Soln'),
  ('Risedronate Sodium'),
  ('Risperidone'),
  ('Ritodrine Hcl'),
  ('Ritonavir'),
  ('Rituximab'),
  ('Rivastigmine'),
  ('Rocuronium'),
  ('Ropinirole'),
  ('Rosiglitazone'),
  ('Rosuvastatin'),
  ('Rosuvastatin Calcium'),
  ('Rotavirus Vaccine'),
  ('Roxatidine'),
  ('Roxithromycin'),
  ('Rubella Vaccine'),
  ('Ruscogenin'),
  ('Sacchoromyces Boulardii'),
  ('Salbutamol'),
  ('Salcatonin'),
  ('Salicylazosulphapyridine'),
  ('Salicylic Acid'),
  ('Salicylic Acid/Lactic Acid'),
  ('Salmeterol'),
  ('Secnidazole'),
  ('Selegiline'),
  ('Selenium Sulphide'),
  ('Serratiopeptidase'),
  ('Sertraline'),
  ('Sevoflurane'),
  ('Sibutramine Hydrochloride'),
  ('Silicon Dioxide'),
  ('Silver Sulphadiazine'),
  ('Silymarin'),
  ('Simethicone'),
  ('Simethicone+Al Hydroxide+Mg Hydroxide'),
  ('Simvastatin'),
  ('Simvastatin+Ezetimibe'),
  ('Sitagliptin'),
  ('Sitagliptin Phosphate'),
  ('Sitgaliptin+Metformin Hcl'),
  ('Soda Mint'),
  ('Sodium 2-Mercaptoethane Sulfonate'),
  ('Sodium Acid Citrate'),
  ('Sodium Alginate'),
  ('Sodium Alphaoxybenzyl Phosphinic Acid'),
  ('Sodium Chloride 0.45%'),
  ('Sodium Chloride 0.65%'),
  ('Sodium Chloride 0.9%'),
  ('Sodium Chloride 2%'),
  ('Sodium Chloride+Tranexamic Acid'),
  ('Sodium Clodronate'),
  ('Sodium Cromoglycate'),
  ('Sodium Diatrizoate'),
  ('Sodium Fusidate'),
  ('Sodium Iodide'),
  ('Sodium Monophlorophosphate'),
  ('Sodium Nitroprusside'),
  ('Sodium Picosulphate'),
  ('Sodium Pyrrolidone Carboxylate'),
  ('Sodium Stibogluconate'),
  ('Sodium Valproate'),
  ('Solifenacin Succinate'),
  ('Somatostatin Acetate'),
  ('Somatropin'),
  ('Sorbide Nitrate'),
  ('Soybean Oil'),
  ('Sparfloxacin'),
  ('Spiramycin'),
  ('Spironolactone'),
  ('Spironolactone Frusemide'),
  ('Stanozalol'),
  ('Stavudine'),
  ('Streptokinase'),
  ('Streptomycin'),
  ('Strontium Chloride'),
  ('Succinyl Choline'),
  ('Sucraflate+Calcium Carbonate'),
  ('Sucralfate'),
  ('Sulbactam'),
  ('Sulbutiamine'),
  ('Sulfadoxine'),
  ('Sulfamethoxazole-Trimethoprim'),
  ('Sulfasalazine'),
  ('Sulphacetamide Sodium'),
  ('Sulphadiazine'),
  ('Sulphadimidine'),
  ('Sulphanilacarbamide'),
  ('Sulphanilamide'),
  ('Sulphasalazine'),
  ('Sulphonamide/Diaminopyrimidine'),
  ('Sulphur'),
  ('Sulpiride'),
  ('Sumatriptan Succinate'),
  ('Sunitinib'),
  ('Suxamethonium'),
  ('Tacalcitol'),
  ('Tacrolimus'),
  ('Tamoxifen'),
  ('Tamsulosin Hydrochloride'),
  ('Tazobactam'),
  ('Tegaserod'),
  ('Telbuvidine'),
  ('Telcoplanin'),
  ('Telithromycin'),
  ('Telmisartan'),
  ('Telmisartan+Amlodipine'),
  ('Telmisartan+Hydrochlorothiazide'),
  ('Temazepam'),
  ('Tenoxicam'),
  ('Terazosin Hcl'),
  ('Terbinafine'),
  ('Terbutaline'),
  ('Teriparatide'),
  ('Terlipressin'),
  ('Terpineol'),
  ('Testosteron Enanthate'),
  ('Testosteron Isocaproate'),
  ('Testosteron Oenanthate'),
  ('Testosteron Phenylpropionate'),
  ('Testosteron Propionate'),
  ('Testosteron Undecanoate'),
  ('Testosterone Decanoate'),
  ('Tetanus Antitoxin'),
  ('Tetanus Immunoglobulin'),
  ('Tetanus Toxoid Adsorbed'),
  ('Tetanus Vaccine'),
  ('Tetrachlorodecaooxide'),
  ('Tetracycline(& Salts)'),
  ('Tetrahydrofuryl-5-Fluorouracil'),
  ('Tetrahydrozolin'),
  ('Thalidomide'),
  ('Theophylline'),
  ('Theophylline Ethylene Diamine'),
  ('Thiacetazone'),
  ('Thiethyleperazain Meleate'),
  ('Thiocolchicoside'),
  ('Thioguanine'),
  ('Thiopental Sodium'),
  ('Thiopentone Sodium'),
  ('Thioridazine'),
  ('Thymomodulin'),
  ('Thymosine Alpha'),
  ('Thyroxine Sodium'),
  ('Tiapentine Sodium'),
  ('Tibezonium Iodide'),
  ('Tibolone'),
  ('Ticarcillin'),
  ('Tice Bcg'),
  ('Ticlopidine'),
  ('Timolol Maleat'),
  ('Tinidazole'),
  ('Tinzaparin'),
  ('Tioconazole'),
  ('Tirofiban'),
  ('Tiropramide'),
  ('Tizanidine'),
  ('Tobramycin'),
  ('Tobramycin+Dexamethasone'),
  ('Tofisopam'),
  ('Tolperisone Hcl'),
  ('Tolterodine'),
  ('Topiramate'),
  ('Tramadol Hcl'),
  ('Trandolapril'),
  ('Tranexamic Acid'),
  ('Trastuzumab'),
  ('Travoprost'),
  ('Trazodone'),
  ('Tretinoin'),
  ('Triamcinolone Acetonide'),
  ('Triamterene'),
  ('Triclofos Sodium'),
  ('Triclosan'),
  ('Trifluoperazine'),
  ('Trihexyphenidyl'),
  ('Trimebutine Maleate'),
  ('Trimetazidine Hcl'),
  ('Trimethoprim'),
  ('Trimethylphloroglucinol'),
  ('Triprolidine'),
  ('Triptorelin'),
  ('Tromantadine'),
  ('Tropicamide'),
  ('Tropisteron Hcl'),
  ('Trypsin'),
  ('Ttfd/Fursufiamine'),
  ('Tulobuterol Hcl'),
  ('Typhoid Vaccine'),
  ('Tyrothricin Benzocain'),
  ('Ubidecarenone/Q 10 Co-Enzyme'),
  ('Ubiquinone'),
  ('Urofollitrophin'),
  ('Urosodeoxycholic Acid'),
  ('Valacyclovir'),
  ('Valdecoxib'),
  ('Valganciclovir'),
  ('Valsartan'),
  ('Valsartan+Amlodipine'),
  ('Valsartan+Hydrochlorothiazide 25Mg'),
  ('Vancomycin'),
  ('Varenicline'),
  ('Varicella Virus Vaccine'),
  ('Vecuronium Bromide'),
  ('Venlafaxine'),
  ('Verapamil'),
  ('Verteporfin'),
  ('Vinblastine'),
  ('Vincristine'),
  ('Vinorelbine'),
  ('Vinpocetine'),
  ('Vit A'),
  ('Vit A.D,E'),
  ('Vit B1'),
  ('Vit B12'),
  ('Vit B6'),
  ('Vit C'),
  ('Vit Calcium+D3'),
  ('Vit D3'),
  ('Vit E'),
  ('Vit K'),
  ('Vitamin A C E Complex'),
  ('Vitamin B1+B6+B12'),
  ('Warfarin'),
  ('Yellow Fever Vaccine'),
  ('Zafirlukast'),
  ('Zalcitabine'),
  ('Zidovudine'),
  ('Zinc Oxide'),
  ('Zinc Pyrithione'),
  ('Zinc Sulfate Monohydrate'),
  ('Zinc Sulphate'),
  ('Ziprasidone'),
  ('Zoledronic Acid'),
  ('Zolmitriptan'),
  ('Zolpidem Hemitartrate'),
  ('Zuclopenthixol')
ON CONFLICT (lower(name)) DO NOTHING;

INSERT INTO manufacturers (name) VALUES
  ('3S PHARMACEUTICAL (PVT) LTD'),
  ('A S TRADERS'),
  ('ABBOTT'),
  ('ACCURATE MEDICAL'),
  ('ACME'),
  ('ADAM JEE PHARMA (PVT)LTD'),
  ('ADCOK PHARMACEUTICAL'),
  ('AGP'),
  ('AKHAI PHARMA DUBBLE'),
  ('AKSON PHARMA'),
  ('AL HAMEED AGENCIES'),
  ('AL SAUDIA TIBBI FOND.'),
  ('AL-HABIB PHARMA'),
  ('AL-SAUDIA TIBI FOUNDATION'),
  ('AL-SHAFI COSMETICS LAHORE'),
  ('ALAQ LABORATORIES'),
  ('ALBRO CHEMISTS'),
  ('ALCON'),
  ('ALI GOHAR'),
  ('ALLERGAN'),
  ('ALLMED (PVT)LTD'),
  ('ALMIVAL'),
  ('ALPINE PHARMA PVT LTD.'),
  ('AMBROSIA PHARMACEUTICAL'),
  ('AMITY WORLD'),
  ('AMROS PHARMACEUTICAL'),
  ('AMSON FARMACO.'),
  ('ANGEL'),
  ('ANGEL PHARMMACEUTICAL .'),
  ('ANSEL'),
  ('ANTIBIOTICS.'),
  ('ARIES PHARMA PESHAWER'),
  ('ARROW'),
  ('AS TRADERS'),
  ('ASTRAPANECA'),
  ('ATCO'),
  ('AULTON PHARMACEUTICAL'),
  ('AUS.BODYCARE UK'),
  ('AVENSIS PHARMACEUTICAL'),
  ('AVENTIS/SANOFI'),
  ('Akhai Pharma (pvt)Ltd'),
  ('Al Falah Health Care Pvt. Ltd.'),
  ('Amarant Pharmaceutical'),
  ('B-BRUAN.'),
  ('B.D'),
  ('BABAR BILAL C/O TARIQ SAHB'),
  ('BAJWA PHARMACEUTICAL PVT.LTD'),
  ('BAKREY ITEMS'),
  ('BARRETT HODGSON'),
  ('BAYER'),
  ('BECTON DICKINSON SERVICE.'),
  ('BEECHAM'),
  ('BEKAZ ALTERNATE THP.'),
  ('BENSON PHARMACEUTICALS'),
  ('BENTLEY'),
  ('BIO PHARMA'),
  ('BIO ROOTS LAB.(PVT) LTD'),
  ('BIO TECH PHARMA'),
  ('BIOCARE'),
  ('BIOGEN LIFE SCIENCES'),
  ('BIOGENICES PAKISTAN PVT LTD'),
  ('BIOGLAN PHARMA PAKISTAN'),
  ('BIOMAXX PHARMA'),
  ('BIOREX PHARMA'),
  ('BIOTEQ'),
  ('BIOTEST'),
  ('BIOVISTA PVT LTD'),
  ('BIQ PHARMA'),
  ('BLEES PHARMA'),
  ('BLOOM/OLIVE'),
  ('BMI'),
  ('BODE COMPANEY'),
  ('BONE ENERGIZER/SUNRAY PHARMA.'),
  ('BOSCH'),
  ('BRACCO'),
  ('BRIMLY'),
  ('BRISTOL'),
  ('BROOKS PHARMA'),
  ('BRYON'),
  ('BSN MEDICAL'),
  ('BUCKLEYS'),
  ('BURNA'),
  ('BUTT & SONS'),
  ('BYER'),
  ('CAC 1000 PLUS 20 TAB'),
  ('CALGAN PHYTO PHARMA(PVT) LTD'),
  ('CANDELEY'),
  ('CANDID PHARMACEUTICALS'),
  ('CARAWAY PHARMA CEUTICALS'),
  ('CARAWAY PHARMACEUTICAL'),
  ('CCL Pharmaceurical(Pvt)Ltd.'),
  ('CELL LAB.(PVT) LTD'),
  ('CENTEON'),
  ('CENTURY PAHRMACEUTICAL(PVT)LTD'),
  ('CERTEZA'),
  ('CHEMOTECMICA'),
  ('CHIESI'),
  ('CHINA'),
  ('CHINA PRODUCT'),
  ('CHISHTI'),
  ('CHOSMETICS'),
  ('CIBEX (PVT) LIMITED.'),
  ('CINTEC PHARMACEUTCAL'),
  ('CIRIN'),
  ('CLR MEDICAL'),
  ('COMBAT EURASIAN PHARMA'),
  ('COMBINOO LIFE SCIENCES'),
  ('COMFORT'),
  ('CONTINENTAL PHARMA'),
  ('COOL ITEMS'),
  ('COX PHARMA.'),
  ('CREST PHARMACEUTICAL'),
  ('CROWN PHARMACEUTICALS ISB.'),
  ('CRYSTOLITE PHARMA'),
  ('CSH'),
  ('CSL BEHRING'),
  ('CURA MEDICAL'),
  ('CURE INN PHARMACEUTICAL'),
  ('CYNOSURE (PVT) LTD'),
  ('DANAS PHARMA (PVT) LTD.'),
  ('DAWNRAYS PHARMA'),
  ('DELMA INTRNL NUTRACEUTICALS.'),
  ('DELTA PHARMA PVT. LTD.'),
  ('DENK PHARMA'),
  ('DERMA TECHNO'),
  ('DERMA VISION'),
  ('DERMAGEN PHARMA'),
  ('DIPERSA/CIBA'),
  ('DONGKOOK PHARM.CO'),
  ('DORMIS BIOLOGICAL'),
  ('DOSACO LAB'),
  ('DRIPS'),
  ('DUPLEX PHARMA'),
  ('DYSON RESEARCH'),
  ('ED MERCK'),
  ('EFROZE'),
  ('ELICE PHARMA'),
  ('ELITE PHARMA'),
  ('ELIXER LABORATORIES'),
  ('ELKO'),
  ('ENDOWMED'),
  ('ENGLISH PHARMA'),
  ('EPLA'),
  ('EPOCH PHARMA'),
  ('ETC'),
  ('ETHICAL'),
  ('ETHICAL LABORATORIES'),
  ('ETHICONE'),
  ('EURODRUG.'),
  ('EVEREST PHARMACEUTICAL'),
  ('EXELL HEALTHCARE LAB'),
  ('FABIMILK'),
  ('FADA PHARMA'),
  ('FAIR LABORTARIES.'),
  ('FAISAL PHARMA.'),
  ('FAROOQ'),
  ('FAROOQI MARKITING'),
  ('FARSER PHARMA.'),
  ('FEATHER'),
  ('FERING'),
  ('FEROZA INTERNATIONAL'),
  ('FEROZSONS LAB'),
  ('FLOW PHARMA.'),
  ('FORAY'),
  ('FORTE PHARMA'),
  ('FOZAN PHARMA'),
  ('FOZAR ENT'),
  ('FRIENDS PHARMA'),
  ('FRIENDS PHARMA (pvt)LTD'),
  ('FRONTIER PHARMA'),
  ('FUJI'),
  ('FYNK PHARMA'),
  ('GASTRO CARE & BIOCARE'),
  ('GENBIOTECH NUTRACEUTICAL'),
  ('GENERAL/STENLAY'),
  ('GENESIS PHARMA'),
  ('GENETICS PH'),
  ('GENIX PHRAMA'),
  ('GENOME PHARMACEUTICALS PVT.LTD'),
  ('GENRAL ITEMS MIX'),
  ('GEOFMAN PHARMA'),
  ('GETZ PHARMA'),
  ('GHAYYOOR PHARMACEUTICAL.'),
  ('GLAXO SMITH KLINE'),
  ('GLAXO WELCOME'),
  ('GLITS PHARMA'),
  ('GLOBAL PHARMA'),
  ('GMBH & CO.KG'),
  ('GOLDSHEFF PHARMA'),
  ('GOODMAN INT.'),
  ('GREEN PHARMA X'),
  ('GREENSTAR SOCIAL MARKETING'),
  ('GRY-S PHARMA'),
  ('GSK'),
  ('GUYTON PHARMA'),
  ('HABBIT'),
  ('HADI PHARMACEUTICAL'),
  ('HALICON'),
  ('HAMAZ PHARMA MULTAN.'),
  ('HANSEL PH'),
  ('HARMANN PHARMA LAB.'),
  ('HAROONI INTERNATIONAL'),
  ('HARRISON PHARMA'),
  ('HAVEN PHARACEUTICAL'),
  ('HEALTHTEK(PVT)LIMITED'),
  ('HELIX PHARMA'),
  ('HELIX/HAKIMSONS'),
  ('HELTON'),
  ('HI-TECH.'),
  ('HIBA INTERNATIONAL'),
  ('HIGH-Q PHARMA'),
  ('HIGHNOON LAB'),
  ('HILTON PHARMA'),
  ('HILTON PHARMA (PVT) LTD.'),
  ('HIMONT PHARMA'),
  ('HOFFMAN HUMAN HEALTH PAK LTD'),
  ('HOME CARE CHINA'),
  ('HONIG PHARMA LAB'),
  ('HONIG PHARMACEUTICAL'),
  ('HONIG PHARMACEUTICALS'),
  ('HOOVER PHARMA (PVT) LTD'),
  ('HOWARD'),
  ('HUCKERTS'),
  ('HUMDARD'),
  ('HYAN PHARMA'),
  ('HYGEIA PHARMA'),
  ('HYGEIA PHARMACEUTICALS'),
  ('Health Care Surgical'),
  ('I.B.I'),
  ('ICI/MARTIN DOW'),
  ('ILDONG'),
  ('IMAAN PHARMACY.'),
  ('IMP./Stenly'),
  ('INDUS PHARMA'),
  ('INJACKT .'),
  ('INNVOTEK PHARMACETICALS'),
  ('INSAF'),
  ('IPI IDEAL'),
  ('IPRAM'),
  ('IRZA'),
  ('ISIS PHARMACEUTICAL IND.'),
  ('ISLAM PHARMACEUTICAL'),
  ('Indus pharma'),
  ('J.A ENTERPRISES'),
  ('JAENS NEUTRACEUTICAL'),
  ('JAENS PHARMA'),
  ('JASKAN PHARMACEUTICAL'),
  ('JAWA PHARMACEUTICAL'),
  ('JENNER PHAMACEUTICAL(PVT) LTD.'),
  ('JHONSONS & JHONSONS'),
  ('JMS'),
  ('JNS INTERNATIONAL (PVT) LTD.'),
  ('JULPHAR PHARMA'),
  ('JnS INTERNATIONAL PVT LTD LHR'),
  ('K & K CHINA'),
  ('KANEL LABORATORIES.'),
  ('KARACHI CHEMICAL IND'),
  ('KARIL STORZ'),
  ('KARKA'),
  ('KENDLE'),
  ('KERASON PHARMA'),
  ('KHONSTAMM PHARMA'),
  ('KOBEC PHARMA'),
  ('LABOC PHARMA'),
  ('LAHORE CHEMICAL & PHARMA'),
  ('LAHORE PHARMA'),
  ('LAWRENCE PHARMA'),
  ('LDS (PVT) LTD'),
  ('LEADS PHARMA'),
  ('LEDERLE'),
  ('LEO PHARMA'),
  ('LEXICON PHARMA'),
  ('LG LIFE SCIENCES'),
  ('LHR PHARMA/UNI MARK'),
  ('LIFE INTERNATIONAL'),
  ('LIFE LINE'),
  ('LIFE SCIENCES'),
  ('LILLY'),
  ('LINTA PHARMA'),
  ('LINZ PHARMA'),
  ('LISKO PAKISTAN (PVT).'),
  ('LIVER RITE'),
  ('LOCAL PURCHASE'),
  ('LOWITT PHARMA'),
  ('LUHARI'),
  ('M&H MANUFACTURING CO'),
  ('M.D.'),
  ('MAC & RAINS'),
  ('MACTER'),
  ('MADREX LABORATORY'),
  ('MAHA'),
  ('MANAWER'),
  ('MAPLE PHARMA'),
  ('MAQ PHARMACEUTICAL'),
  ('MARTIN DOW LIMITED'),
  ('MARTIN DOW MARKER LTD'),
  ('MARTIN DOW PHARMA'),
  ('MASON PHARMA'),
  ('MASS PHARMA'),
  ('MASTER'),
  ('MATRIX PHARMA'),
  ('MCOLSON RESEARCH LABORATORY'),
  ('MEDCOMP'),
  ('MEDERA PHARMA'),
  ('MEDEVO PVT LTD'),
  ('MEDI AIMS MARKETING'),
  ('MEDI STAR 2020'),
  ('MEDI-MILLENNIUM'),
  ('MEDIATE PHARMA (PVT)LMT'),
  ('MEDICEENA PHARMA'),
  ('MEDICEENA.'),
  ('MEDICOM SUPERIOR'),
  ('MEDICOS'),
  ('MEDICRAFT'),
  ('MEDICRAFT PHARMCEUTICALS'),
  ('MEDIFORMERS PHARMA'),
  ('MEDILINE PHARMA'),
  ('MEDIPAK LTD SURGICAL'),
  ('MEDISAVE PHARMA'),
  ('MEDISAVE PHARMACEUTICALS'),
  ('MEDISEARCH PHARMA'),
  ('MEDITRONIC'),
  ('MEDIZAN LAB (PVT) LTD'),
  ('MEDSOL'),
  ('MEDWAY PHARMA LAHORE'),
  ('MEGA PHARMA'),
  ('MELIOR PHARMA'),
  ('MENDOZA'),
  ('MERCK SHARP & DOHME'),
  ('MEZAN INTERNATIONAL'),
  ('MIKSON HEALTHCARE(PVT)LTD.'),
  ('MILESTONE TRADERS'),
  ('MIX'),
  ('MORINAGA'),
  ('MOUJ NUTRACEUTICAL'),
  ('MSD PHARMA'),
  ('MTI Medical Pvt Ltd'),
  ('MULTI HEALTH PHARMA'),
  ('MUNAWAR PHARMA'),
  ('MURFY PHARMACEUTICAL'),
  ('N.B.S. PHARMA'),
  ('NABI QASIM'),
  ('NABIQASIM'),
  ('NAPRO PHARMA'),
  ('NAVEGAL(WEBROS)Phrama'),
  ('NEO NEXUS PAKISTAN LTD'),
  ('NEOMEDIX'),
  ('NEPMEDIX PH'),
  ('NESTLE'),
  ('NEUCON PH'),
  ('NEUCON PHARMA'),
  ('NEUTRO PHARMA(PVT)LTD.'),
  ('NEW-MASTER'),
  ('NEXPHARM PHARMA'),
  ('NICOLEST PHARMA'),
  ('NIMRALL PHARMA'),
  ('NISA PHARMA'),
  ('NORTECH PHARMACEUTICAL PVT.LTD'),
  ('NOVAMED PHARMA'),
  ('NOVARTIS'),
  ('NOVINS INTERNATIONAL'),
  ('NOVINS PHARMA'),
  ('NOVO NORDISK'),
  ('NUTRABIOTICS LIFE SCIENCE'),
  ('NUTRISER HEALTH CARE'),
  ('NUZZER PHARMA'),
  ('OBSONS PHARMACETICALA'),
  ('OCEAN PAHARMA.'),
  ('OCTA PHARMA'),
  ('OLIVE LAB (MAX PHARMA)'),
  ('ONTECH CORPORATION'),
  ('OPAL PHARMA'),
  ('OPHTH-PHARMA'),
  ('OPTIMUS PHARMA (PVT) LTD'),
  ('ORBIT NUTRACEUTICALS'),
  ('ORGANON'),
  ('ORIGIN PHARMA PVT LTD'),
  ('ORTA LAB (PVT) LTD'),
  ('ORTA LABORATORIES.'),
  ('OTSUKA'),
  ('OVAL PHARMA'),
  ('P.D.H'),
  ('PACER INTERNATIONAL.'),
  ('PACIFIC'),
  ('PACIFIC-LEPTIT'),
  ('PAK RISEN PHARMACEUTICALS'),
  ('PAKSOL'),
  ('PAKTEX IDUSTRIES'),
  ('PANACEA PHARMA'),
  ('PARAMOUNT PHARMA'),
  ('PARKE DAVIS'),
  ('PAYER PHARMA'),
  ('PDH'),
  ('PEARL PH'),
  ('PEARL PHARMACEUTICALS'),
  ('PERFECT'),
  ('PFIZER'),
  ('PHARMA LABS(Pharmevo)'),
  ('PHARMACARE LAB'),
  ('PHARMAEVO'),
  ('PHARMAGEN.'),
  ('PHARMATEC'),
  ('PHARMAWISE LAB'),
  ('PHARMEDIC'),
  ('PHARMEVO'),
  ('PHARMIX LABORTORIES'),
  ('PHONIX ENGLAND'),
  ('PHYTOCON INTERNATIONAL'),
  ('PLATINUM PHARMA'),
  ('PLIVA PAKISTAN (PVT).'),
  ('PLIVA PAKISTAN LTD'),
  ('POLFENE CHEMPHARMA LTD'),
  ('POLYFINE CHEM PHARMA'),
  ('POPULER INTERNATIONAL'),
  ('PRAYS PHARMACEUTICAL(GEN TAK)'),
  ('PREMIER AGENCIES'),
  ('PRIDE PHARMA'),
  ('PULSE PHARMA'),
  ('PUR'),
  ('Public Patient Care'),
  ('QUARSHI'),
  ('R.Y INT'),
  ('R.Y.INTERNATIONAL'),
  ('RAAZEE THERAPEUTICS PVT)LTD'),
  ('RAINBOW NATURAL PHARMA'),
  ('RASCO PHARMA'),
  ('RAYMOND PHARMA'),
  ('RAYUON.'),
  ('RECKITT & COLMAN'),
  ('REDEX PHARMA .'),
  ('REGENT LABORATORIES KARACHI'),
  ('REHMAT PHARMA LAHORE'),
  ('REKO PHARMACAL'),
  ('REMEDIES INTERNATIONAL'),
  ('REMIGTON+KOBEC'),
  ('RICKER'),
  ('ROCHESTER MADICAL'),
  ('ROTEX PHARMA(PVT)LTD.'),
  ('ROUCHE UK'),
  ('ROYAL LAB'),
  ('S.HAROONI INTERNATIONAL'),
  ('S.J.G FAZAL ELAHIE'),
  ('SAFE PHARMACEUTICAL'),
  ('SAFFI MEDICOSE PARMACEUTICAL'),
  ('SAFFRON PHARMECAL.'),
  ('SALMORE PHARMACEUTICAL'),
  ('SALVUS/SALBION PHARMA'),
  ('SAMI PHARMA'),
  ('SANDOZ PHARMA'),
  ('SANITAL PHARMA'),
  ('SANOFI AVENTIS'),
  ('SANTE PVT LIMITED'),
  ('SANTE.'),
  ('SAVOUR'),
  ('SAYDON PHARMA.'),
  ('SAYYED PHARMA.'),
  ('SCHAZOO'),
  ('SCHERING'),
  ('SCHERING PHARMA'),
  ('SCILIFE PHARMA(PVT) LTD.'),
  ('SCOTMAN PHARMACEUTICALS'),
  ('SEARLE'),
  ('SELCO PHARMACEUTICAL'),
  ('SEMOS PHARMA (PVT) LTD.'),
  ('SERVIER RESEARCH PHARMA'),
  ('SERVIPHARM'),
  ('SEVEN HERBAL PHARMACY'),
  ('SHAHEEN PARMACEUTICAL'),
  ('SHAIGAN'),
  ('SHANGHAI PHARMA'),
  ('SHARPON'),
  ('SHAZAL''S PHARMACEUTICAL'),
  ('SHIAGON'),
  ('SHIELD.'),
  ('SHIFA.'),
  ('SHIN POONG PHARMA .CO.LTD'),
  ('SHROOQ PHARAMCEUTICAL'),
  ('SHROOQ PHARMA'),
  ('SINDHCO LAB.'),
  ('SIZA INT'),
  ('SIZA INTERNATIONAL'),
  ('SJ&G. Fazul Ellahie(Pvt) Ltd.'),
  ('SK&F VIKOR ENT'),
  ('SLIMFIT'),
  ('SMITHNEPHU'),
  ('SOCIAL MARKETING'),
  ('SONEXO PHARMA'),
  ('SPECTERM'),
  ('SPECTRUM LAB'),
  ('SQUIBB'),
  ('SRA MEDICAL'),
  ('STANDERD CHEM PHARMA'),
  ('STANDPHARM'),
  ('STANDPHARM GREEN'),
  ('STANELY PHARMA'),
  ('STAR'),
  ('STERLING PHARMACEUTICALS'),
  ('STIFFEL'),
  ('SUCCESS PHARMACEUTICAL'),
  ('SUFI SONS MARKETING'),
  ('SULK PHARMA'),
  ('SUNSHINE ARTHOPEADIC SERVICES'),
  ('SUPPLIMENTS'),
  ('SURGE LABORATORIES'),
  ('SURGICAL'),
  ('SURGICAL TEXTILE'),
  ('SWISS PHARMA'),
  ('SYNTEX PHARMA'),
  ('Superior Wellness(Pvt)Ltd'),
  ('TABROS PHARMA'),
  ('TAG SYRINGES(PVT)'),
  ('TAGMA'),
  ('TAGMA PHARMA (Pvt)Ltd.'),
  ('TARROT PHARMA PRIVATE. LTD.'),
  ('TAS PHARMA'),
  ('TASMIYAH INTERNATIONAL'),
  ('TECHNOVISION PHARMACEUTICALS'),
  ('TEDITECH PHARMA'),
  ('THAMES PHARMACRUTICALS'),
  ('TITLIS PHARMA'),
  ('TRANS WORLD PH'),
  ('TREAD PAK'),
  ('TREAD PHARMACEUTICAL'),
  ('TRIGON'),
  ('TRIGON PHARMACEUTICALS'),
  ('UNEXCO'),
  ('UNIMARK PHARMA'),
  ('UNISON CHEMICAL WORKS'),
  ('UNITED INTERNATIONAL'),
  ('UNIVERSAL PHARMA'),
  ('UP JOHN'),
  ('UPPAL PHARMA'),
  ('VALOR PH'),
  ('VALOR PHARMA'),
  ('VARIOLINE'),
  ('VASOCEN B BROWN'),
  ('VASOFIX'),
  ('VEGA PHARMA'),
  ('VELENTINE PHARMA'),
  ('VENTURE(ISLAMABAD DIS)'),
  ('VENTURE. KOREAN'),
  ('VENUS'),
  ('VERIZON SURGICAL'),
  ('VERMONT'),
  ('VERTEX COSMETICS'),
  ('VISION PHARMA'),
  ('W I PAK'),
  ('WAGMA MAR.SER'),
  ('WARBLE'),
  ('WASCO INT'),
  ('WATAN DISTRIBUTARS'),
  ('WEATHER FOLDS PHARMA'),
  ('WEBROS PHARMA'),
  ('WEL MARK'),
  ('WEL WINK PHARMA'),
  ('WELLBORNE PHARMA'),
  ('WELMARK PHARMACEUTICAL'),
  ('WELMARK PHARMACEUTICALS'),
  ('WERRICK PHARMA'),
  ('WERRICK PHARMACEUTICAL'),
  ('WIL SONS'),
  ('WILSHAR LABORATORY(PVT) LTD'),
  ('WILSON''S PHARMA'),
  ('WINBRAINS RESEARCH LAB.'),
  ('WINTHROX PVT LTD.'),
  ('WIPAK INTERNATIONAL'),
  ('WISE PHARMA'),
  ('WNSFEILD PHARMACEUTICAL'),
  ('WOODWARDS PAKISTAN (PVT) LTD.'),
  ('WYETH'),
  ('XENON'),
  ('YOKO HIGHT (JAPAN)'),
  ('YOUNAS TRADERS'),
  ('YUNG SHIN PHARMA'),
  ('Z-JANS'),
  ('ZAARCO PHARMACEUTICALS'),
  ('ZAFA PHARMA'),
  ('ZAMKO PHARMACUTICAL(PVT) LTD'),
  ('ZEENUSH'),
  ('ZODIAC PHARMA'),
  ('gluck')
ON CONFLICT (lower(name)) DO NOTHING;

-- Shelf groups, so a new install can classify a medicine straight away.
INSERT INTO product_groups (name) VALUES
  ('Tablets'), ('Capsules'), ('Syrups'), ('Injections'), ('Infusions'),
  ('Drops'), ('Ointments'), ('Sachets'), ('Inhalers'), ('Surgical'),
  ('Cosmetics'), ('Other')
ON CONFLICT (lower(name)) DO NOTHING;
