import { createContext, useCallback, useContext, useEffect, useState, type ReactNode } from 'react'

/**
 * Appearance and language, held in one place.
 *
 * Both are per-machine rather than per-account: a reception desk in a bright
 * front room and a radiology console in a dark room want different themes even
 * when the same person signs in at both. localStorage is the right scope for
 * that; the server has no opinion about either.
 */

export type Theme = 'classic' | 'slate' | 'dark'
type Lang = 'en' | 'ur'

type Prefs = {
  theme: Theme
  lang: Lang
  setTheme: (t: Theme) => void
  toggleTheme: () => void
  setLang: (l: Lang) => void
  t: (key: string) => string
}

/** Classic is the default: the palette this ran on before, borders fixed. */
export const THEMES: { id: Theme; label: string; note: string; swatch: string[] }[] = [
  { id: 'classic', label: 'Classic', note: 'Soft blue-white',
    swatch: ['#EFF4F8', '#FFFFFF', '#109ED8'] },
  { id: 'slate', label: 'Slate', note: 'Cooler, more contrast',
    swatch: ['#D6E2EC', '#FFFFFF', '#0E84B8'] },
  { id: 'dark', label: 'Dark', note: 'For dim rooms',
    swatch: ['#0E151E', '#222F3E', '#38AFE2'] }
]

const PrefsContext = createContext<Prefs | null>(null)

function read<T extends string>(key: string, fallback: T): T {
  try { return (localStorage.getItem(key) as T) || fallback } catch { return fallback }
}

export function PrefsProvider({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<Theme>(() => {
    const saved = read<Theme>('hms.theme', 'classic')
    return THEMES.some((t) => t.id === saved) ? saved : 'classic'
  })
  const [lang, setLangState] = useState<Lang>(() => read('hms.lang', 'en'))

  useEffect(() => {
    const root = document.documentElement
    for (const t of THEMES) root.classList.remove(`theme-${t.id}`)
    root.classList.add(`theme-${theme}`)
    // `dark` is kept as its own class so Tailwind's dark: variants still work.
    root.classList.toggle('dark', theme === 'dark')
    try { localStorage.setItem('hms.theme', theme) } catch { /* private mode */ }
  }, [theme])

  useEffect(() => {
    const root = document.documentElement
    root.setAttribute('lang', lang)
    /**
     * Deliberately left as ltr.
     *
     * Urdu is written right to left, but mirroring the whole interface moves
     * every button and column someone has already learned the position of, and
     * the tables here are full of Latin numerals, MRNs and medicine names that
     * read left to right anyway. Translating the words without moving the
     * furniture is the smaller change and the one staff asked for.
     */
    root.setAttribute('dir', 'ltr')
    root.classList.toggle('lang-ur', lang === 'ur')
    try { localStorage.setItem('hms.lang', lang) } catch { /* private mode */ }
  }, [lang])

  // Kept in a module variable as well as in state, so the bare `t()` export
  // below can be called from anywhere — including plain helper functions that
  // are not React components and cannot use a hook. Every screen sits under
  // this provider, so a language change re-renders them all and they read the
  // new value on the way through.
  currentLang = lang
  const translate = useCallback((key: string) => translateWith(lang, key), [lang])

  return (
    <PrefsContext.Provider value={{
      theme, lang,
      setTheme: setThemeState,
      toggleTheme: () => setThemeState((t) => (t === 'dark' ? 'classic' : 'dark')),
      setLang: setLangState,
      t: translate
    }}>
      {children}
    </PrefsContext.Provider>
  )
}

let currentLang: Lang = 'en'

function translateWith(lang: Lang, key: string): string {
  if (lang === 'en') return key
  return UR[key] ?? key
}

/**
 * Translate a string.
 *
 * Callable outside React on purpose: much of the interface text lives in
 * helper functions and option arrays rather than inside a component body, and
 * threading a hook through all of them would be worse than reading one module
 * variable.
 */
export function t(key: string): string {
  return translateWith(currentLang, key)
}

export function usePrefs(): Prefs {
  const c = useContext(PrefsContext)
  if (!c) throw new Error('usePrefs used outside PrefsProvider')
  return c
}

/** Shorthand, since translation is the thing screens reach for constantly. */
export const useT = () => usePrefs().t

/**
 * Urdu strings, keyed by the English text itself.
 *
 * Keying on English rather than on codes means an untranslated string falls
 * back to readable English instead of showing a raw key like `nav.patients`.
 * In a bilingual hospital that is the right failure: staff read both, and a
 * half-translated screen still works.
 *
 * Clinical shorthand (OD, BD, TDS), medicine names, drug strengths and
 * anything printed on a legal document stay in English on purpose — that is
 * what pharmacists and doctors here actually read and write.
 */
const UR: Record<string, string> = {
  "&deg;F": "°F",
  "1 amp IV": "ایک ایمپیول IV",
  "1 tablet": "ایک گولی",
  "10 tablets in a strip = 10": "ایک پتے میں دس گولیاں = 10",
  "30 days": "تیس دن",
  "50 x 25 mm labels, one per medicine. Set the label roll as the default printer before printing these.": "۵۰ × ۲۵ ملی میٹر لیبل، ہر دوا کے لیے ایک۔ چھاپنے سے پہلے لیبل رول کو ڈیفالٹ پرنٹر بنا لیں۔",
  "58mm roll": "۵۸ ملی میٹر رول",
  "7 days": "سات دن",
  "80mm roll": "۸۰ ملی میٹر رول",
  "90 days": "نوے دن",
  "A carton of 100 gloves = 100": "۱۰۰ دستانوں کا کارٹن = ۱۰۰",
  "A hospital number is generated automatically.": "ہسپتال نمبر خودبخود بن جاتا ہے۔",
  "A return is always against the bill it was sold on": "واپسی ہمیشہ اُسی بل کے خلاف ہوتی ہے جس پر فروخت ہوا",
  "A voucher number is issued and the ledger is posted at once.": "واؤچر نمبر جاری ہو گا اور کھاتہ فوراً درج ہو جائے گا۔",
  "A-3": "اے-۳",
  "A4 sheet": "اے فور شیٹ",
  "AP view": "اے پی ویو",
  "Accept the return": "واپسی قبول کریں",
  "Access": "رسائی",
  "Account Title": "کھاتے کا نام",
  "Accounts with a balance": "بقایا والے کھاتے",
  "Actually on the shelf": "اصل میں شیلف پر",
  "Add": "شامل کریں",
  "Add a line": "سطر شامل کریں",
  "Add an item to this delivery": "اس ترسیل میں شے شامل کریں",
  "Add details": "تفصیل شامل کریں",
  "Add details instead": "بجائے اس کے تفصیل درج کریں",
  "Add item": "شے شامل کریں",
  "Add medicine": "دوا شامل کریں",
  "Add one under Administration, Staff. Tick Pharmacy administrator to let it set other people's access.": "انتظامیہ، عملہ میں جا کر بنائیں۔ دوسروں کی رسائی طے کرنے کے لیے فارمیسی منتظم پر نشان لگائیں۔",
  "Add service": "سروس شامل کریں",
  "Add something this test uses": "اس ٹیسٹ میں استعمال ہونے والی شے شامل کریں",
  "Add staff": "عملہ شامل کریں",
  "Add the first one": "پہلی اندراج کریں",
  "Add the tests and scans this hospital offers, with their prices.": "اس ہسپتال کے ٹیسٹ اور اسکین قیمتوں سمیت درج کریں۔",
  "Add to the patient's account": "مریض کے کھاتے میں شامل کریں",
  "Add what was actually used at the bedside. The pharmacy collects for it afterwards.": "جو دوا واقعی مریض پر استعمال ہوئی وہ درج کریں۔ فارمیسی بعد میں رقم وصول کرے گی۔",
  "Address": "پتہ",
  "Administration": "انتظامیہ",
  "Administrator": "منتظم",
  "Administrators": "منتظمین",
  "Admit arrivals and record bedside medicines": "آمد داخل کریں اور بستر پر دی گئی ادویات درج کریں",
  "Admit to emergency": "ایمرجنسی میں داخل کریں",
  "Admitted to ward": "وارڈ میں داخل",
  "Advice": "ہدایات",
  "After meals": "کھانے کے بعد",
  "Age": "عمر",
  "Age in years": "عمر بسال",
  "Age/Sex": "عمر/جنس",
  "All": "تمام",
  "All categories": "تمام اقسام",
  "All companies": "تمام کمپنیاں",
  "All departments": "تمام شعبے",
  "All doctors": "تمام ڈاکٹر",
  "All patients": "تمام مریض",
  "All suppliers": "تمام سپلائر",
  "Allergies": "الرجی",
  "Allow pop-ups for this site to print.": "چھاپنے کے لیے اس سائٹ کی پاپ اپ اجازت دیں۔",
  "Already expired": "میعاد ختم شدہ",
  "Already recorded": "پہلے درج شدہ",
  "Amount": "رقم",
  "Amount from (Rs)": "رقم از (روپے)",
  "Amounts": "رقوم",
  "Amounts are your share, not what the patient was billed.": "یہ رقوم آپ کا حصہ ہیں، مریض کا کل بل نہیں۔",
  "Anything else the doctor should know": "کوئی اور بات جو ڈاکٹر کو معلوم ہونی چاہیے",
  "Anything not collected is waiting at the pharmacy counter to be paid for.": "جو نہیں لی گئی وہ فارمیسی کاؤنٹر پر ادائیگی کی منتظر ہے۔",
  "Anything the doctor ordered will appear above, ready to print.": "ڈاکٹر کا تجویز کردہ ہر ٹیسٹ اوپر پرنٹ کے لیے آ جائے گا۔",
  "Appearance": "ظاہری شکل",
  "Applied to anything they order, unless overridden per test under Doctor shares": "ہر تجویز پر لاگو، جب تک ڈاکٹر کے حصے میں الگ شرح مقرر نہ ہو",
  "Archive": "محفوظ کریں",
  "Archived": "محفوظ شدہ",
  "Asif Mahmood": "آصف محمود",
  "At a glance": "ایک نظر میں",
  "At least 8 characters": "کم از کم آٹھ حروف",
  "At or below the level you set, most urgent first": "مقررہ حد پر یا اس سے کم، سب سے ضروری پہلے",
  "Available for doctors to order": "ڈاکٹر تجویز کر سکتے ہیں",
  "Awaiting payment": "ادائیگی کا منتظر",
  "Awaiting sample": "نمونے کا انتظار",
  "B+": "بی مثبت",
  "BP diastolic": "بلڈ پریشر نچلا",
  "BP systolic": "بلڈ پریشر اوپری",
  "Back": "واپس",
  "Back to the list": "فہرست پر واپس",
  "Backups": "بیک اپ",
  "Balance": "بقایا",
  "Barcode": "بارکوڈ",
  "Batch": "بیچ",
  "Batches close to their date, soonest first": "میعاد کے قریب بیچ، جلد ختم ہونے والے پہلے",
  "Beats per minute": "دھڑکن فی منٹ",
  "Begin": "شروع کریں",
  "Best sellers": "سب سے زیادہ فروخت",
  "Bill": "بل",
  "Bill complete": "بل مکمل",
  "Bill no from": "بل نمبر از",
  "Bill no ↑": "بل نمبر ↑",
  "Bill no ↓": "بل نمبر ↓",
  "Bill numbers": "بل نمبر",
  "Bill total": "بل کی کل رقم",
  "Billed": "بل شدہ",
  "Billed to patients": "مریضوں سے وصول",
  "Billing": "بلنگ",
  "Bills": "بل",
  "Blank lines at the end": "آخر میں خالی سطریں",
  "Blood (EDTA)": "خون (EDTA)",
  "Blood (Plain)": "خون (سادہ)",
  "Blood group": "بلڈ گروپ",
  "Blood sugar": "شوگر",
  "Bonus": "بونس",
  "Bring back": "واپس لیں",
  "Brought in by": "لانے والا",
  "Brought in with": "کس حالت میں لایا گیا",
  "By": "بذریعہ",
  "By doctor": "بلحاظ ڈاکٹر",
  "By patient": "بلحاظ مریض",
  "By revenue in this window": "اس مدت کی آمدنی کے حساب سے",
  "CNIC": "شناختی کارڈ",
  "Came with attendant, cannot walk unaided": "ساتھی کے ہمراہ آیا، بغیر سہارے نہیں چل سکتا",
  "Can be sold loose, a few units at a time": "کھلی فروخت ممکن ہے",
  "Cancel": "منسوخ کریں",
  "Cannot be started": "شروع نہیں ہو سکتا",
  "Card and wallets": "کارڈ اور والٹ",
  "Cash box": "کیش باکس",
  "Cash received": "وصول شدہ نقد",
  "Cash taken": "وصول شدہ نقد",
  "Cash up": "کیش گنتی",
  "Cashier": "کیشیئر",
  "Category": "قسم",
  "Change": "تبدیل کریں",
  "Change to give": "واپس کرنے کی رقم",
  "Charged to the patient": "مریض سے وصول",
  "Check the dates and the totals before printing.": "چھاپنے سے پہلے تاریخیں اور میزان دیکھ لیں۔",
  "Check the dates and the totals. Print sends this page to the printer; Download saves a PDF.": "تاریخیں اور میزان دیکھ لیں۔ پرنٹ یہ صفحہ پرنٹر کو بھیجتا ہے؛ ڈاؤن لوڈ پی ڈی ایف محفوظ کرتا ہے۔",
  "Checking…": "جانچ جاری ہے…",
  "Cheque number, slip number": "چیک نمبر، سلپ نمبر",
  "Chit": "پرچی",
  "Chit no, MRN, name, phone or token": "پرچی نمبر، ایم آر این، نام، فون یا ٹوکن",
  "Chits": "پرچیاں",
  "Chits and payments": "پرچیاں اور ادائیگیاں",
  "Chits appear on their own as soon as the doctor orders a test or scan.": "ڈاکٹر کے ٹیسٹ یا اسکین تجویز کرتے ہی پرچیاں خودبخود آ جاتی ہیں۔",
  "Chits shown": "دکھائی گئی پرچیاں",
  "Choose a doctor": "ڈاکٹر منتخب کریں",
  "Choose a supplier": "سپلائر منتخب کریں",
  "Choose an item": "شے منتخب کریں",
  "Classic": "کلاسک",
  "Clear the search to see the whole queue.": "پوری قطار دیکھنے کے لیے تلاش صاف کریں۔",
  "Close": "بند کریں",
  "Close this emergency visit?": "یہ ایمرجنسی وزٹ بند کریں؟",
  "Close visit": "وزٹ بند کریں",
  "Closing balance": "اختتامی بقایا",
  "Closing the visit does not cancel this. It stays collectable.": "وزٹ بند کرنے سے یہ ختم نہیں ہوتا۔ رقم بدستور واجب الادا رہتی ہے۔",
  "Code": "کوڈ",
  "Collapse": "سکیڑیں",
  "Collected at the main counter": "مین کاؤنٹر پر وصول ہوتی ہے",
  "Comes off the store now": "ابھی اسٹور سے کم ہو گا",
  "Comment on this test, printed under its results": "اس ٹیسٹ پر تبصرہ، نتائج کے نیچے چھپے گا",
  "Comments": "تبصرہ",
  "Company": "کمپنی",
  "Complaint": "شکایت",
  "Complaint and readings": "شکایت اور ریڈنگ",
  "Complete bill": "بل مکمل کریں",
  "Completed": "مکمل",
  "Condition": "حالت",
  "Confirm": "تصدیق کریں",
  "Confirm password": "پاس ورڈ کی تصدیق",
  "Consultation": "معائنہ",
  "Consultation fee": "ڈاکٹر کی فیس",
  "Consultation fee and the share they keep": "ڈاکٹر کی فیس اور اُن کا حصہ",
  "Consultation fee, then the queue. The doctor can order tests afterwards.": "ڈاکٹر کی فیس، پھر قطار۔ ڈاکٹر بعد میں ٹیسٹ تجویز کر سکتا ہے۔",
  "Consultation fees": "ڈاکٹر کی فیسیں",
  "Consultation fees collected": "وصول شدہ ڈاکٹر فیس",
  "Consultation fees, last {hours} hours": "ڈاکٹر فیس، پچھلے گھنٹے",
  "Consultations, prescriptions and ordering tests": "معائنہ، نسخے اور ٹیسٹ تجویز کرنا",
  "Consumables used by the hospital, not sold to patients": "ہسپتال کے استعمال کی اشیاء، مریضوں کو فروخت نہیں ہوتیں",
  "Controlled — prescriber required": "ممنوعہ — نسخہ لازمی",
  "Cooler, more contrast": "ٹھنڈا، زیادہ نمایاں",
  "Copies": "کاپیاں",
  "Cost": "لاگت",
  "Cost each": "فی عدد لاگت",
  "Count": "گنتی",
  "Counter": "کاؤنٹر",
  "Counter, stock, ledgers and reports": "کاؤنٹر، اسٹاک، کھاتے اور رپورٹیں",
  "Counts": "گنتیاں",
  "Cover": "دورانیہ",
  "Cr": "جمع",
  "Credit": "جمع",
  "Credited to their account": "اُن کے کھاتے میں جمع",
  "Critical": "تشویشناک",
  "Customer": "گاہک",
  "Customer balances": "گاہکوں کا بقایا",
  "Customers": "گاہک",
  "Daily takings": "روزانہ آمدنی",
  "Damaged": "خراب",
  "Dark": "گہرا",
  "Dark mode": "ڈارک موڈ",
  "Date": "تاریخ",
  "Date range": "تاریخ کی حد",
  "Days of history": "کتنے دن کا ریکارڈ",
  "Debit": "نام",
  "Decide later": "بعد میں طے کریں",
  "Decide later leaves them registered with nothing owing. You can find them again by name or MRN.": "بعد میں طے کریں سے وہ رجسٹر رہیں گے اور کچھ واجب الادا نہ ہو گا۔ نام یا ایم آر این سے دوبارہ تلاش کر سکتے ہیں۔",
  "Decide what other staff can do": "طے کریں کہ دوسرا عملہ کیا کر سکتا ہے",
  "Default": "طے شدہ",
  "Default on tests": "ٹیسٹ پر طے شدہ",
  "Default share of tests (%)": "ٹیسٹ میں طے شدہ حصہ (٪)",
  "Delete patient": "مریض حذف کریں",
  "Delete permanently": "مستقل حذف کریں",
  "Delete this patient?": "یہ مریض حذف کریں؟",
  "Deleting…": "حذف ہو رہا ہے…",
  "Deliveries": "ترسیلات",
  "Delivery received": "ترسیل وصول ہوئی",
  "Delivery total": "ترسیل کل",
  "Demo data": "نمونہ ڈیٹا",
  "Demo data loaded": "نمونہ ڈیٹا لوڈ ہو گیا",
  "Department": "شعبہ",
  "Departments": "شعبہ جات",
  "Detail": "تفصیل",
  "Diagnosis": "تشخیص",
  "Diagnosis and advice": "تشخیص اور ہدایات",
  "Died": "وفات",
  "Discharged": "فارغ",
  "Discount": "رعایت",
  "Discount given": "دی گئی رعایت",
  "Dispense against prescriptions": "نسخوں پر دوا دیں",
  "Doctor": "ڈاکٹر",
  "Doctor details": "ڈاکٹر کی تفصیل",
  "Doctor earnings": "ڈاکٹر کی آمدنی",
  "Doctor gets": "ڈاکٹر کو ملے گا",
  "Doctor keeps (%)": "ڈاکٹر رکھے گا (٪)",
  "Doctor shares": "ڈاکٹر کا حصہ",
  "Doctor terminal": "ڈاکٹر ٹرمینل",
  "Doctor's share (%)": "ڈاکٹر کا حصہ (٪)",
  "Doctors": "ڈاکٹر صاحبان",
  "Done": "مکمل",
  "Dopahar": "دوپہر",
  "Download": "ڈاؤن لوڈ",
  "Download PDF": "پی ڈی ایف ڈاؤن لوڈ کریں",
  "Dr": "نام",
  "Dr Yasir Habib": "ڈاکٹر یاسر حبیب",
  "Dressing trolley restock": "ڈریسنگ ٹرالی بھرنے کے لیے",
  "Drop": "ختم کریں",
  "Duty doctor": "ڈیوٹی ڈاکٹر",
  "Each gets its own report number, but only one sample is taken.": "ہر ایک کا اپنا رپورٹ نمبر ہو گا، مگر نمونہ ایک ہی لیا جائے گا۔",
  "Each test saves as its own report. Once every field is filled, the whole visit prints as one document with a page per test.": "ہر ٹیسٹ اپنی الگ رپورٹ بنتا ہے۔ تمام خانے بھرنے پر پورا وزٹ ایک ہی دستاویز میں چھپتا ہے، ہر ٹیسٹ کے لیے الگ صفحہ۔",
  "Each test saves as its own report. Saving takes what they use off the store.": "ہر ٹیسٹ اپنی الگ رپورٹ کے طور پر محفوظ ہوتا ہے۔ محفوظ کرنے پر استعمال شدہ اشیاء اسٹور سے کم ہو جاتی ہیں۔",
  "Each unit inside is called": "اندر ہر یونٹ کہلاتا ہے",
  "Earned": "کمائی",
  "Earnings": "آمدنی",
  "Edit": "ترمیم",
  "Edit patient": "مریض میں ترمیم",
  "Edit results": "نتائج تبدیل کریں",
  "Emergency": "ایمرجنسی",
  "Emergency floor": "ایمرجنسی فلور",
  "Emergency — admissions and bedside medicines": "ایمرجنسی — داخلے اور بستر پر دی گئی ادویات",
  "English": "انگریزی",
  "Enter results": "نتائج درج کریں",
  "Enter what one": "لکھیں کہ ایک",
  "Evening": "شام",
  "Every report in the hospital, read only": "ہسپتال کی ہر رپورٹ، صرف پڑھنے کے لیے",
  "Everyone": "سب",
  "Everyone ever registered, most recently seen first": "اب تک رجسٹرڈ تمام مریض، حالیہ پہلے",
  "Everyone who can sign in": "ہر وہ فرد جو داخل ہو سکتا ہے",
  "Everything": "سب کچھ",
  "Everything in and out, oldest kept for good": "ہر آمد و رفت، پرانا ریکارڈ مستقل محفوظ",
  "Everything is settled": "سب کچھ برابر ہے",
  "Everything on this invoice has already been returned.": "اس بل کی تمام اشیاء پہلے ہی واپس ہو چکی ہیں۔",
  "Expand": "پھیلائیں",
  "Expires": "میعاد",
  "Expiring": "میعاد قریب",
  "Expiring soon": "جلد میعاد ختم",
  "Expiring stock": "میعاد قریب اسٹاک",
  "Expiring within 90 days": "نوے دن میں میعاد ختم",
  "Expiry": "میعاد",
  "Expiry risk": "میعاد کا خطرہ",
  "Expiry watch": "میعاد کی نگرانی",
  "Faster at a busy window, but a wrong bill is printed before anyone sees it": "مصروف کاؤنٹر پر تیز، مگر غلط بل کسی کے دیکھنے سے پہلے چھپ جائے گا",
  "Father or husband": "والد یا شوہر",
  "Father's or husband's name": "والد یا شوہر کا نام",
  "Fee": "فیس",
  "Fee collected now": "ابھی وصول شدہ فیس",
  "Fees collected": "وصول شدہ فیس",
  "Fees collected against each": "ہر ایک کے مقابل وصول شدہ فیس",
  "Female": "عورت",
  "Fever for three days": "تین دن سے بخار",
  "Fever for three days, headache": "تین دن سے بخار، سر درد",
  "File": "فائل",
  "Fill this at the counter": "کاؤنٹر پر یہ نسخہ پورا کریں",
  "Filled": "بھرے گئے",
  "Filling a prescription": "نسخہ پورا کیا جا رہا ہے",
  "Find": "تلاش کریں",
  "Find or register a patient": "مریض تلاش یا رجسٹر کریں",
  "Find the invoice": "بل تلاش کریں",
  "Fine if the complaint does not call for it. Otherwise add them first.": "اگر شکایت تقاضا نہ کرے تو ٹھیک ہے۔ ورنہ پہلے تفصیل درج کریں۔",
  "Finished": "مکمل",
  "Footer on chits": "پرچی پر نیچے کی تحریر",
  "Footer on receipts": "رسید پر نیچے کی تحریر",
  "For a patient buying medicines outside. Set the paper to A5 in the print dialog.": "باہر سے دوا خریدنے والے مریض کے لیے۔ پرنٹ ڈائیلاگ میں کاغذ A5 مقرر کریں۔",
  "For department use": "شعبے کے استعمال کے لیے",
  "For dim rooms": "کم روشنی کے لیے",
  "For how many days": "کتنے دن کے لیے",
  "Formula": "فارمولا",
  "Formula and shelf": "فارمولا اور شیلف",
  "From": "از",
  "From consultations": "مشوروں سے",
  "From tests and scans": "ٹیسٹ اور اسکین سے",
  "Front desk": "فرنٹ ڈیسک",
  "Full access, including staff and rates": "مکمل رسائی، عملہ اور نرخ سمیت",
  "Full name": "پورا نام",
  "GEN": "جنرل",
  "Gender": "جنس",
  "General Medicine": "جنرل میڈیسن",
  "General Physician": "جنرل فزیشن",
  "Generic name": "جنرک نام",
  "Get well soon.": "جلد صحت یاب ہوں۔",
  "Gets every pharmacy tab, and an Access tab for deciding what the other pharmacy staff can see and do.": "فارمیسی کے تمام ٹیبز ملیں گے، اور ایک رسائی ٹیب جس سے طے ہو گا کہ باقی فارمیسی عملہ کیا دیکھ اور کر سکتا ہے۔",
  "Give back": "واپس کریں",
  "Give back as": "کس صورت میں واپس",
  "Give the patient the chit. They can take it to the department now.": "مریض کو پرچی دے دیں۔ وہ اب شعبے میں لے جا سکتے ہیں۔",
  "Given to": "وصول کرنے والا",
  "Grand Total": "کل میزان",
  "Gross margin": "مجموعی منافع",
  "Group": "گروپ",
  "Hides what this hospital is not using yet. Nothing is deleted.": "جو ابھی استعمال میں نہیں، وہ چھپا دیتا ہے۔ کچھ حذف نہیں ہوتا۔",
  "High": "زیادہ",
  "Highest first": "زیادہ پہلے",
  "Hold the queue and record vitals": "قطار سنبھالیں اور ابتدائی معائنہ لکھیں",
  "Holds the queue and records vitals before the doctor": "قطار سنبھالتا ہے اور ڈاکٹر سے پہلے علامات درج کرتا ہے",
  "Hospital": "ہسپتال",
  "Hospital consumables and supplies": "ہسپتال کی استعمالی اشیاء اور سامان",
  "Hospital consumables — gauze, gloves, IV sets": "ہسپتال کی اشیاء — گاز، دستانے، ڈرپ سیٹ",
  "Hospital details": "ہسپتال کی تفصیل",
  "Hospital keeps": "ہسپتال رکھے گا",
  "How": "کیسے",
  "How it is sold": "فروخت کا طریقہ",
  "How many": "کتنی",
  "How much each time": "ہر بار کتنی مقدار",
  "How people paid": "ادائیگی کا طریقہ",
  "How sick are they?": "حالت کتنی سنگین ہے؟",
  "INV-4471": "INV-4471",
  "Imaging list": "امیجنگ فہرست",
  "In stock": "موجود اسٹاک",
  "In units, not packs": "یونٹ میں، پیک میں نہیں",
  "In use": "استعمال میں",
  "Instructions": "ہدایات",
  "Invoice": "انوائس",
  "Invoice date": "انوائس کی تاریخ",
  "Invoice number": "انوائس نمبر",
  "Invoice number, e.g. S-000412": "بل نمبر، مثلاً S-000412",
  "Invoice total": "انوائس کل",
  "Invoice, customer, phone or an amount": "انوائس، گاہک، فون یا رقم",
  "Invoices": "بل",
  "Issue": "جاری کریں",
  "Issue to a department": "کسی شعبے کو جاری کریں",
  "Issued": "جاری شدہ",
  "Issued in": "جاری کرنے کی اکائی",
  "Item": "شے",
  "Items": "اشیاء",
  "Keep the record": "ریکارڈ رہنے دیں",
  "Keep this bill for any return or exchange.": "واپسی یا تبدیلی کے لیے یہ بل سنبھال رکھیں۔",
  "Keeps": "رکھتا ہے",
  "Keeps of that": "اس میں سے رکھتا ہے",
  "Known allergies": "معلوم الرجی",
  "Lab": "لیب",
  "Laboratory": "لیبارٹری",
  "Laboratory — samples and results": "لیبارٹری — نمونے اور نتائج",
  "Language": "زبان",
  "Last 24 hours": "پچھلے چوبیس گھنٹے",
  "Last 3 days": "پچھلے تین دن",
  "Last 30 days": "پچھلے تیس دن",
  "Last 7 days": "پچھلے سات دن",
  "Last 8 hours": "پچھلے آٹھ گھنٹے",
  "Last 90 days": "پچھلے نوے دن",
  "Last Entry": "آخری اندراج",
  "Last seen": "آخری بار",
  "Lateral": "لیٹرل",
  "Leave blank if unknown": "معلوم نہ ہو تو خالی چھوڑ دیں",
  "Leave blank to use what you typed above": "خالی چھوڑ دیں تو اوپر لکھا نام استعمال ہو گا",
  "Ledgers": "کھاتے",
  "Left against advice": "مشورے کے خلاف چلا گیا",
  "Light mode": "لائٹ موڈ",
  "Line": "سطر",
  "Loading demo data": "نمونہ ڈیٹا لوڈ ہو رہا ہے",
  "Loading…": "لوڈ ہو رہا ہے…",
  "Low": "کم",
  "Low stock": "کم اسٹاک",
  "Lower": "نچلا",
  "Lowest first": "کم پہلے",
  "MRN": "ایم آر این",
  "Main counter": "مین کاؤنٹر",
  "Main counter window": "مین کاؤنٹر ونڈو",
  "Main counter — registration and payments": "مین کاؤنٹر — رجسٹریشن اور ادائیگیاں",
  "Male": "مرد",
  "Manage suppliers": "سپلائر سنبھالیں",
  "Margin": "منافع",
  "Mark done": "مکمل قرار دیں",
  "Medicine": "دوا",
  "Medicine labels": "دوا کے لیبل",
  "Medicines": "ادویات",
  "Medicines to collect": "لینے والی ادویات",
  "Modules in use": "زیرِ استعمال ماڈیول",
  "Money": "رقم",
  "Monthly count, boxes found behind the shelf": "ماہانہ گنتی، شیلف کے پیچھے ڈبے ملے",
  "Morning": "صبح",
  "Most recent first": "حالیہ پہلے",
  "Most used items": "سب سے زیادہ استعمال ہونے والی اشیاء",
  "Movements": "نقل و حرکت",
  "Muslim Distributors": "مسلم ڈسٹری بیوٹرز",
  "My earnings": "میری آمدنی",
  "My patients": "میرے مریض",
  "NOT PAID — DO NOT PROCEED": "ادائیگی نہیں ہوئی — کارروائی نہ کریں",
  "NTN": "این ٹی این",
  "Name": "نام",
  "Name or code": "نام یا کوڈ",
  "Name, MRN or phone": "نام، ایم آر این یا فون",
  "Name, MRN, phone or CNIC": "نام، ایم آر این، فون یا شناختی کارڈ",
  "Name, MRN, token or phone": "نام، ایم آر این، ٹوکن یا فون",
  "Name, generic, company or barcode": "نام، جنرک، کمپنی یا بارکوڈ",
  "Name, or search for an existing patient": "نام، یا پہلے سے موجود مریض تلاش کریں",
  "Name, phone number, MRN or CNIC": "نام، فون نمبر، ایم آر این یا شناختی کارڈ",
  "Nearest expiry": "قریب ترین میعاد",
  "Nearest expiry goes out first, automatically": "قریب ترین میعاد پہلے جاتی ہے، خودبخود",
  "New arrival": "نئی آمد",
  "New password": "نیا پاس ورڈ",
  "New patient": "نیا مریض",
  "Newest": "نیا ترین",
  "Next 90 days": "اگلے نوے دن",
  "Next customer": "اگلا گاہک",
  "Next patient": "اگلا مریض",
  "No backups yet": "ابھی کوئی بیک اپ نہیں",
  "No bills match that": "اس سے مطابقت رکھنے والا کوئی بل نہیں",
  "No chits yet": "ابھی کوئی پرچی نہیں",
  "No complaint recorded": "کوئی شکایت درج نہیں",
  "No consultations yet": "ابھی کوئی مشورہ نہیں",
  "No deliveries recorded yet": "ابھی کوئی ترسیل درج نہیں",
  "No details have been recorded for this patient yet": "اس مریض کی ابھی کوئی تفصیل درج نہیں ہوئی",
  "No doctor and no consultation fee. The patient pays for the tests only, and the department sees them as soon as the bill is completed.": "نہ ڈاکٹر، نہ فیس۔ مریض صرف ٹیسٹ کی رقم ادا کرتا ہے، اور بل مکمل ہوتے ہی شعبہ انہیں دیکھ لیتا ہے۔",
  "No doctor and no consultation fee. They pay for the tests and go straight to the department.": "نہ ڈاکٹر، نہ فیس۔ وہ صرف ٹیسٹ کی رقم ادا کر کے سیدھا شعبے میں جاتے ہیں۔",
  "No doctors set up yet": "ابھی کوئی ڈاکٹر مقرر نہیں",
  "No item called that. Register it first, then receive stock against it.": "اس نام کی کوئی شے نہیں۔ پہلے رجسٹر کریں، پھر اس کے خلاف اسٹاک وصول کریں۔",
  "No items on this delivery note yet": "اس ترسیل میں ابھی کوئی شے نہیں",
  "No money is taken here: the consultation and any tests are paid at the main counter, and medicines at the pharmacy.": "یہاں رقم وصول نہیں ہوتی: ڈاکٹر کی فیس اور ٹیسٹ مین کاؤنٹر پر، ادویات فارمیسی پر ادا ہوتی ہیں۔",
  "No name given. Fine for an unconscious patient — the record can be renamed later.": "نام درج نہیں۔ بے ہوش مریض کے لیے ٹھیک ہے — ریکارڈ بعد میں تبدیل ہو سکتا ہے۔",
  "No panel set up for this test, so write the finding in full. An administrator can add reference ranges under Services.": "اس ٹیسٹ کا پینل مقرر نہیں، اس لیے نتیجہ پورا لکھیں۔ منتظم سروسز میں حوالہ حدود شامل کر سکتا ہے۔",
  "No pharmacy accounts yet": "ابھی کوئی فارمیسی اکاؤنٹ نہیں",
  "No sales in this window": "اس مدت میں کوئی فروخت نہیں",
  "No sales yet": "ابھی کوئی فروخت نہیں",
  "No services set up yet. An admin adds these.": "ابھی کوئی سروس مقرر نہیں۔ منتظم یہ شامل کرتا ہے۔",
  "No services yet": "ابھی کوئی سروس نہیں",
  "Nobody else waiting": "اور کوئی منتظر نہیں",
  "Nobody has been sent in yet": "ابھی کوئی نہیں بھیجا گیا",
  "Nobody in emergency": "ایمرجنسی میں کوئی نہیں",
  "Nobody in this role yet.": "اس ذمہ داری پر ابھی کوئی نہیں۔",
  "Nobody in this window": "اس مدت میں کوئی نہیں",
  "Nobody matches that. Register them as a new patient if you are sure.": "کوئی مطابقت نہیں ملی۔ یقین ہو تو نیا مریض رجسٹر کریں۔",
  "Nobody matching": "کوئی مطابقت نہیں",
  "Nobody sent in yet": "ابھی کوئی نہیں بھیجا گیا",
  "Nobody waiting": "کوئی منتظر نہیں",
  "Nobody yet": "ابھی کوئی نہیں",
  "None": "کوئی نہیں",
  "Noon": "دوپہر",
  "Normal reading": "عام نتیجہ",
  "Not applicable": "لاگو نہیں",
  "Not grouped": "گروپ نہیں",
  "Not in this drawer": "اس دراز میں نہیں",
  "Not in use": "استعمال میں نہیں",
  "Not linked": "منسلک نہیں",
  "Not paid yet": "ابھی ادائیگی نہیں",
  "Not recorded": "درج نہیں",
  "Not yet printed": "ابھی پرنٹ نہیں ہوئی",
  "Note": "نوٹ",
  "Notes": "نوٹ",
  "Nothing earned in this period": "اس مدت میں کوئی آمدنی نہیں",
  "Nothing expiring in that window": "اس مدت میں کوئی میعاد ختم نہیں",
  "Nothing expiring soon": "جلد کوئی میعاد ختم نہیں ہو رہی",
  "Nothing here": "یہاں کچھ نہیں",
  "Nothing issued yet": "ابھی کچھ جاری نہیں ہوا",
  "Nothing matches that": "کوئی مطابقت نہیں",
  "Nothing needs reordering": "کسی دوا کا آرڈر درکار نہیں",
  "Nothing on the bench for this patient": "اس مریض کا کوئی کام زیرِ عمل نہیں",
  "Nothing on the bill yet.": "بل میں ابھی کچھ نہیں۔",
  "Nothing on this delivery note yet": "اس ترسیل نوٹ پر ابھی کچھ نہیں",
  "Nothing prescribed yet. Anything not stocked can still be written.": "ابھی کوئی دوا تجویز نہیں۔ غیر موجود دوا بھی لکھی جا سکتی ہے۔",
  "Nothing returned today": "آج کوئی واپسی نہیں",
  "Nothing selected": "کچھ منتخب نہیں",
  "Nothing to bill": "بل کے لیے کچھ نہیں",
  "Nothing to label": "لیبل کے لیے کچھ نہیں",
  "Nothing to report for this period": "اس مدت کی کوئی رپورٹ نہیں",
  "Nothing waiting": "کوئی منتظر نہیں",
  "OPD counter": "او پی ڈی کاؤنٹر",
  "OPD counter — queue and vitals": "او پی ڈی کاؤنٹر — قطار اور ابتدائی معائنہ",
  "Oblique": "اوبلیک",
  "Of their own consultation fee": "اپنی مشورہ فیس میں سے",
  "Oldest": "پرانا ترین",
  "On hand": "موجود",
  "On the bench": "زیرِ عمل",
  "On the floor": "فلور پر",
  "One": "ایک",
  "One delivery note, as many items as it covers": "ایک ترسیل نوٹ، جتنی اشیاء اس میں ہوں",
  "One row per line on the report. Leave the range blank for results that are words rather than numbers, and put the expected answer in Normal reading instead.": "رپورٹ کی ہر سطر کے لیے ایک قطار۔ جہاں نتیجہ عدد کے بجائے الفاظ میں ہو، حد خالی چھوڑ کر متوقع جواب عام نتیجہ میں لکھیں۔",
  "One row per patient, not one per transaction": "ہر مریض کی ایک سطر، ہر لین دین کی نہیں",
  "One supplier invoice, as many medicines as it covers": "ایک سپلائر انوائس، جتنی ادویات اس میں ہوں",
  "One test on this visit has no sample yet": "اس وزٹ کے ایک ٹیسٹ کا نمونہ ابھی نہیں لیا گیا",
  "One unit per pack, so the pack price is the same.": "ایک پیک میں ایک اکائی، اس لیے پیک کی قیمت وہی ہے۔",
  "Only": "صرف",
  "Only accounts that are not square": "صرف وہ کھاتے جو برابر نہیں",
  "Only possible while the record has no history. If this patient has ever been seen, billed or prescribed for, the system will refuse and you should correct the details instead.": "صرف اُس وقت ممکن ہے جب ریکارڈ کے ساتھ کوئی تاریخ نہ ہو۔ اگر مریض کبھی دیکھا گیا، بل بنا یا نسخہ لکھا گیا ہو تو نظام انکار کر دے گا؛ ایسی صورت میں تفصیل درست کریں۔",
  "Open": "کھولیں",
  "Opening balance": "ابتدائی بقایا",
  "Optional": "اختیاری",
  "Optional — only where the complaint calls for it": "اختیاری — صرف جہاں شکایت تقاضا کرے",
  "Optional — the printed trade price": "اختیاری — چھپا ہوا ٹریڈ ریٹ",
  "Ordered": "آرڈر شدہ",
  "Ordered but not on a chit": "تجویز شدہ مگر کسی پرچی پر نہیں",
  "Ordered by a doctor, paid at the main counter": "ڈاکٹر کا تجویز کردہ، مین کاؤنٹر پر ادا شدہ",
  "Ordering doctor earns": "تجویز کرنے والے ڈاکٹر کی آمدنی",
  "Other": "دیگر",
  "Out of range": "حد سے باہر",
  "Out of stock": "اسٹاک ختم",
  "Outstanding": "واجب الادا رقم",
  "Over the counter": "عام دستیاب",
  "Override what a specific doctor earns from a specific test. Blank means the default applies.": "کسی مخصوص ڈاکٹر کی کسی مخصوص ٹیسٹ سے آمدنی الگ مقرر کریں۔ خالی رہے تو طے شدہ شرح لاگو ہو گی۔",
  "Overview": "خلاصہ",
  "Owed": "واجب الادا",
  "Owed to doctors": "ڈاکٹروں کو واجب الادا",
  "Owed to us": "ہمیں ملنا ہے",
  "PA view": "پی اے ویو",
  "PAID": "ادا شدہ",
  "Pack is called": "پیک کہلاتا ہے",
  "Packs": "پیک",
  "Page": "صفحہ",
  "Paid": "ادا شدہ",
  "Paid by": "ادائیگی بذریعہ",
  "Paid for at the pharmacy": "فارمیسی پر ادائیگی",
  "Paid in advance": "پیشگی ادا شدہ",
  "Paid, not yet done": "ادا شدہ، ابھی مکمل نہیں",
  "Panadol 500mg": "پیناڈول ۵۰۰ ملی گرام",
  "Paper": "کاغذ",
  "Paracetamol": "پیراسیٹامول",
  "Particulars": "تفصیل",
  "Password": "پاس ورڈ",
  "Patient": "مریض",
  "Patient pays": "مریض ادا کرے گا",
  "Patient sent to the doctor": "مریض ڈاکٹر کے پاس بھیج دیا گیا",
  "Patient, MRN, test or report number": "مریض، ایم آر این، ٹیسٹ یا رپورٹ نمبر",
  "Patients": "مریض",
  "Patients appear here as you send them to a doctor.": "ڈاکٹر کے پاس بھیجے گئے مریض یہاں آتے ہیں۔",
  "Patients arrive here after paying at the main counter": "مریض مین کاؤنٹر پر ادائیگی کے بعد یہاں آتے ہیں",
  "Patients seen": "دیکھے گئے مریض",
  "Patients today": "آج کے مریض",
  "Pay": "ادا کریں",
  "Pay at the cashier before proceeding.": "آگے بڑھنے سے پہلے کیشیئر کو ادائیگی کریں۔",
  "Pay supplier": "سپلائر کو ادائیگی",
  "Payment": "ادائیگی",
  "Payment has been received. The department may proceed.": "ادائیگی وصول ہو چکی ہے۔ شعبہ کارروائی کر سکتا ہے۔",
  "Payment is taken on the next screen. The patient joins the queue once the bill is complete.": "ادائیگی اگلی اسکرین پر لی جائے گی۔ بل مکمل ہوتے ہی مریض قطار میں شامل ہو جائے گا۔",
  "Pending": "زیرِ التوا",
  "Penicillin": "پینسلین",
  "People": "عملہ",
  "Performed by": "کارروائی کرنے والا",
  "Pharmacist": "فارماسسٹ",
  "Pharmacy": "فارمیسی",
  "Pharmacy administrator": "فارمیسی منتظم",
  "Pharmacy staff": "فارمیسی عملہ",
  "Pharmacy till": "فارمیسی کاؤنٹر",
  "Pharmacy — counter, stock and reports": "فارمیسی — کاؤنٹر، اسٹاک اور رپورٹیں",
  "Phone": "فون",
  "Plenty of fluids, rest, return if fever persists past three days": "زیادہ پانی پئیں، آرام کریں، تین دن بعد بھی بخار رہے تو واپس آئیں",
  "Portable": "پورٹیبل",
  "Preparing the document…": "دستاویز تیار ہو رہی ہے…",
  "Preparing…": "تیار ہو رہا ہے…",
  "Prescription": "نسخہ",
  "Prescriptions": "نسخے",
  "Prescriptions to fill": "پورے کرنے والے نسخے",
  "Press New arrival as soon as someone comes through the door.": "کوئی دروازے سے آتے ہی نئی آمد دبائیں۔",
  "Preview receipt": "رسید دیکھیں",
  "Previous visits": "پچھلے دورے",
  "Price": "قیمت",
  "Price, per single unit": "قیمت، فی اکائی",
  "Print": "پرنٹ کریں",
  "Print / PDF": "پرنٹ / پی ڈی ایف",
  "Print chit": "پرچی چھاپیں",
  "Print labels": "لیبل چھاپیں",
  "Print medicine labels": "دوا کے لیبل چھاپیں",
  "Print prescription": "نسخہ چھاپیں",
  "Print receipt": "رسید چھاپیں",
  "Print the chit, take the money, then the patient carries it to the department": "پرچی پرنٹ کریں، رقم وصول کریں، پھر مریض اسے شعبے میں لے جائے",
  "Print the footer message": "نیچے کا پیغام چھاپیں",
  "Print the hospital letterhead": "ہسپتال کا سرنامہ چھاپیں",
  "Printable width": "قابلِ طباعت چوڑائی",
  "Printed": "چھپا",
  "Printed at the top of every chit, receipt and prescription": "ہر پرچی، رسید اور نسخے کے اوپر چھپتا ہے",
  "Printed on the return slip": "واپسی پرچی پر چھپتا ہے",
  "Printed under the results": "نتائج کے نیچے چھپتا ہے",
  "Printing": "پرنٹنگ",
  "Procedure": "طریقہ کار",
  "Procedure completed": "طریقہ کار مکمل",
  "Procedures": "طریقہ ہائے کار",
  "Profit": "منافع",
  "Pulse": "نبض",
  "Purchase": "خرید",
  "Purchase rate": "خرید ریٹ",
  "Purchased": "خریداری",
  "Qty": "تعداد",
  "Queue": "قطار",
  "Queue and vitals": "قطار اور علامات",
  "Queue and vitals — handles no money": "قطار اور ابتدائی معائنہ — رقم نہیں سنبھالتا",
  "Rack": "ریک",
  "Rack location": "ریک کی جگہ",
  "Radiology": "ریڈیالوجی",
  "Radiology — x-ray and imaging": "ریڈیالوجی — ایکسرے اور امیجنگ",
  "Rate": "ریٹ",
  "Read from the ledger, so it does not move if a price changes": "کھاتے سے لیا گیا، اس لیے قیمت بدلنے پر تبدیل نہیں ہوتا",
  "Readings": "ریڈنگ",
  "Reads every report in the hospital and changes nothing": "ہسپتال کی ہر رپورٹ پڑھتا ہے، کچھ تبدیل نہیں کرتا",
  "Ready for you": "آپ کے لیے تیار",
  "Realistic patients, visits, prescriptions and earnings for testing": "جانچ کے لیے حقیقت کے قریب مریض، دورے، نسخے اور آمدنی",
  "Receipt": "رسید",
  "Receive": "وصولی",
  "Receive another": "ایک اور وصول کریں",
  "Receive delivery": "ترسیل وصول کریں",
  "Receive payment": "ادائیگی وصول کریں",
  "Receive stock": "اسٹاک وصول کریں",
  "Received": "وصول شدہ",
  "Received by": "وصول کنندہ",
  "Recent deliveries": "حالیہ ترسیلات",
  "Recent returns": "حالیہ واپسیاں",
  "Recently issued": "حال ہی میں جاری",
  "Reception will send patients through as they arrive.": "استقبالیہ آمد کے ساتھ مریض بھیجتا رہے گا۔",
  "Record it": "درج کریں",
  "Record the count": "گنتی درج کریں",
  "Recorded": "درج شدہ",
  "Records": "ریکارڈ",
  "Reference": "حوالہ حد",
  "Referred by": "بھیجنے والا",
  "Referred out": "باہر ریفر",
  "Refreshes on its own": "خودبخود تازہ ہوتا ہے",
  "Refrigerated": "فریج میں رکھیں",
  "Refund": "واپسی رقم",
  "Register a patient": "مریض رجسٹر کریں",
  "Register a patient or open a chit, and it lands here ready to take payment.": "مریض رجسٹر کریں یا پرچی کھولیں، وہ ادائیگی کے لیے یہاں آ جائے گی۔",
  "Register patients, take fees and settle chits": "مریض رجسٹر کریں، فیس لیں اور پرچیاں نمٹائیں",
  "Registering again is fine if it really is a different person — families share a phone. Picking one above avoids splitting their history across two records.": "اگر واقعی مختلف شخص ہے تو دوبارہ رجسٹر کرنا ٹھیک ہے — گھرانے ایک ہی فون رکھتے ہیں۔ اوپر سے کسی کو منتخب کرنے سے ریکارڈ دو حصوں میں نہیں بٹتا۔",
  "Registration": "رجسٹریشن",
  "Registration, fees and chit payments": "رجسٹریشن، فیس اور پرچی کی ادائیگیاں",
  "Relative, rescue, police": "رشتہ دار، ریسکیو، پولیس",
  "Remove": "ہٹائیں",
  "Reorder at": "دوبارہ آرڈر کی حد",
  "Reorder level": "دوبارہ آرڈر کی حد",
  "Reorder list": "دوبارہ آرڈر کی فہرست",
  "Report": "رپورٹ",
  "Reported": "رپورٹ شدہ",
  "Reported today": "آج رپورٹ شدہ",
  "Reports": "رپورٹیں",
  "Reports — every report, read only": "رپورٹیں — ہر رپورٹ، صرف پڑھنے کے لیے",
  "Required — this is a permanent record": "لازمی — یہ مستقل ریکارڈ ہے",
  "Reset to defaults": "طے شدہ پر واپس لائیں",
  "Restore": "بحال کریں",
  "Result": "نتیجہ",
  "Results saved": "نتائج محفوظ ہو گئے",
  "Retail": "ریٹیل",
  "Retail rate": "ریٹیل ریٹ",
  "Return accepted": "واپسی قبول",
  "Returns": "واپسیاں",
  "Returns today": "آج کی واپسیاں",
  "Revenue": "آمدنی",
  "Road accident, fell from height, chest pain since morning": "ٹریفک حادثہ، بلندی سے گرنا، صبح سے سینے میں درد",
  "Role": "ذمہ داری",
  "Room": "کمرہ",
  "Rs": "روپے",
  "Run the till and hold stock": "کاؤنٹر چلائیں اور اسٹاک رکھیں",
  "Running": "جاری",
  "Sale complete": "فروخت مکمل",
  "Sale price": "فروخت قیمت",
  "Sales": "فروخت",
  "Sample": "نمونہ",
  "Sample not taken — take it from the list, then come back": "نمونہ نہیں لیا گیا — فہرست سے لیں، پھر واپس آئیں",
  "Sample slightly haemolysed": "نمونہ قدرے ہیمولائزڈ",
  "Sample taken": "نمونہ لے لیا گیا",
  "Sample taken?": "نمونہ لے لیا؟",
  "Samples, results and lab reports": "نمونے، نتائج اور لیب رپورٹیں",
  "Samples, results and reports": "نمونے، نتائج اور رپورٹیں",
  "Save": "محفوظ کریں",
  "Save and finish": "محفوظ کریں اور ختم کریں",
  "Save and send in": "محفوظ کریں اور بھیجیں",
  "Save changes": "تبدیلیاں محفوظ کریں",
  "Save results": "نتائج محفوظ کریں",
  "Save what is filled": "جو بھرا ہے محفوظ کریں",
  "Saved": "محفوظ",
  "Saved at": "محفوظ ہوا",
  "Saved. The pharmacy can see this prescription now.": "محفوظ ہو گیا۔ فارمیسی اب یہ نسخہ دیکھ سکتی ہے۔",
  "Saving closes the visit and sends the prescription to the pharmacy.": "محفوظ کرنے پر دورہ بند ہو جائے گا اور نسخہ فارمیسی کو چلا جائے گا۔",
  "Saving closes the visit and sends the prescription to the pharmacy. Print it as well if the patient is buying medicines outside.": "محفوظ کرنے پر دورہ بند ہو جائے گا اور نسخہ فارمیسی کو چلا جائے گا۔ اگر مریض باہر سے دوا لے رہا ہو تو نسخہ چھاپ بھی لیں۔",
  "Saving marks the report ready and takes what this test uses off the store.": "محفوظ کرنے سے رپورٹ تیار ہو جاتی ہے اور استعمال شدہ اشیاء اسٹور سے کم ہو جاتی ہیں۔",
  "Saving…": "محفوظ ہو رہا ہے…",
  "Scan a barcode or search a medicine": "بارکوڈ اسکین کریں یا دوا تلاش کریں",
  "Scan an item, or open the Prescriptions tab to fill a doctor's list.": "کوئی شے اسکین کریں، یا نسخے والا ٹیب کھول کر ڈاکٹر کی فہرست پوری کریں۔",
  "Schedule": "شیڈول",
  "Schedule G — warning shown": "شیڈول جی — انتباہ دکھایا جائے گا",
  "Sealed": "سیل شدہ",
  "Search": "تلاش",
  "Search a formula": "فارمولا تلاش کریں",
  "Search a medicine to add to this delivery": "اس ترسیل میں شامل کرنے کے لیے دوا تلاش کریں",
  "Search a medicine, or type a name and press Enter": "دوا تلاش کریں، یا نام لکھ کر اینٹر دبائیں",
  "Search a test": "ٹیسٹ تلاش کریں",
  "Search above for an item you have already registered.": "اوپر پہلے سے رجسٹر شدہ شے تلاش کریں۔",
  "Search above to add the medicines this invoice covers.": "اس انوائس کی ادویات شامل کرنے کے لیے اوپر تلاش کریں۔",
  "Search an existing patient": "پہلے سے موجود مریض تلاش کریں",
  "Search an item to add to this delivery": "اس ترسیل میں شامل کرنے کے لیے شے تلاش کریں",
  "Search by name, phone, MRN or CNIC before registering. It is the same person more often than it looks.": "رجسٹر کرنے سے پہلے نام، فون، ایم آر این یا شناختی کارڈ سے تلاش کریں۔ اکثر یہ وہی فرد ہوتا ہے۔",
  "See a doctor": "ڈاکٹر سے ملیں",
  "See patient": "مریض دیکھیں",
  "See your patients and prescribe": "اپنے مریض دیکھیں اور نسخہ لکھیں",
  "Seen": "دیکھے گئے",
  "Sell as": "فروخت بطور",
  "Sells at": "فروخت قیمت",
  "Send in": "اندر بھیجیں",
  "Send them to the main counter": "انہیں مین کاؤنٹر بھیجیں",
  "Send this patient in?": "اس مریض کو اندر بھیجیں؟",
  "Send to doctor": "ڈاکٹر کے پاس بھیجیں",
  "Sent in": "بھیجے گئے",
  "Sent in by the OPD counter — details already taken": "او پی ڈی کاؤنٹر نے بھیجا — تفصیل لی جا چکی",
  "Serum": "سیرم",
  "Service": "سروس",
  "Services": "خدمات",
  "Set a reorder level on a medicine to have it appear here.": "کسی دوا کی حد مقرر کریں تو وہ یہاں آئے گی۔",
  "Set up this hospital": "یہ ہسپتال ترتیب دیں",
  "Settings": "ترتیبات",
  "Settle in full": "پورا ادا کریں",
  "Settles to the bank, not the drawer": "بینک میں جاتا ہے، دراز میں نہیں",
  "Setup": "ترتیبات",
  "Sex": "جنس",
  "Shaam": "شام",
  "Short by": "کم ہے",
  "Short code": "مختصر کوڈ",
  "Show this slip at": "یہ پرچی یہاں دکھائیں",
  "Show this slip at the department.": "یہ پرچی شعبے میں دکھائیں۔",
  "Shown to the doctor on every visit": "ہر دورے پر ڈاکٹر کو دکھایا جائے گا",
  "Sickest first, then longest waiting": "زیادہ بیمار پہلے، پھر زیادہ دیر سے منتظر",
  "Sign in as": "بطور داخل ہوں",
  "Sign in with your own account": "اپنے اکاؤنٹ سے داخل ہوں",
  "Sign out": "باہر نکلیں",
  "Signed in as": "بطور داخل",
  "Size": "سائز",
  "Skip the preview and print straight away": "پیش نظارہ چھوڑ کر سیدھا پرنٹ کریں",
  "Skip this if they have never been here or cannot say": "اگر پہلے کبھی نہ آئے ہوں یا بتا نہ سکیں تو چھوڑ دیں",
  "Slate": "سلیٹ",
  "So a pharmacist asked for the generic finds every brand of it": "تاکہ جنرک نام پوچھے جانے پر ہر برانڈ مل جائے",
  "So the tear-off misses the total": "تاکہ کاٹتے وقت کل رقم نہ کٹے",
  "Soft blue-white": "ہلکا نیلا سفید",
  "Software by Ali Farooqi &middot; 0332 4471592": "سافٹ ویئر: علی فاروقی · 0332 4471592",
  "Sold": "فروخت شدہ",
  "Someone already registered looks like this person": "پہلے سے رجسٹرڈ کوئی شخص اِن سے ملتا ہے",
  "Sort": "ترتیب",
  "Specialisation": "تخصص",
  "Staff": "عملہ",
  "Staff, services, prices and reports": "عملہ، خدمات، قیمتیں اور رپورٹیں",
  "Stage": "مرحلہ",
  "Standard": "عام",
  "Start": "شروع کریں",
  "Start the procedure": "طریقہ کار شروع کریں",
  "Start this consultation?": "یہ مشورہ شروع کریں؟",
  "Start this procedure?": "یہ طریقہ کار شروع کریں؟",
  "Starting…": "شروع ہو رہا ہے…",
  "Statement": "گوشوارہ",
  "Status": "حالت",
  "Sterile gauze 10x10cm": "جراثیم سے پاک گاز ۱۰x۱۰ سینٹی میٹر",
  "Still owed": "ابھی واجب الادا",
  "Still to collect": "ابھی وصول کرنا ہے",
  "Still to come": "ابھی آنے والے",
  "Still waiting": "ابھی منتظر",
  "Stock": "اسٹاک",
  "Stock on hand": "موجود اسٹاک",
  "Stock value": "اسٹاک کی مالیت",
  "Stool": "فضلہ",
  "Storage": "ذخیرہ",
  "Store room, shelf B": "اسٹور روم، شیلف بی",
  "Store stock": "اسٹور اسٹاک",
  "Stores": "اسٹور",
  "Stores — hospital consumables": "اسٹور — ہسپتال کی استعمالی اشیاء",
  "Subah": "صبح",
  "Subtotal": "ذیلی میزان",
  "Supplier": "سپلائر",
  "Supplier balances": "سپلائر کا بقایا",
  "Suppliers": "سپلائر",
  "Sutures and IV fluids do. Gloves, linen and instruments do not.": "ٹانکے اور ڈرپ کی میعاد ہوتی ہے۔ دستانے، بستر پوش اور آلات کی نہیں۔",
  "Swab": "سواب",
  "System says": "نظام کے مطابق",
  "TOTAL": "کل",
  "Tablets, syrups, injections": "گولیاں، شربت، انجیکشن",
  "Take another return": "ایک اور واپسی لیں",
  "Take payment": "ادائیگی وصول کریں",
  "Take payment?": "ادائیگی وصول کریں؟",
  "Take sample": "نمونہ لیں",
  "Take this slip to the OPD counter.": "یہ پرچی او پی ڈی کاؤنٹر لے جائیں۔",
  "Take this to the main counter and pay first.": "پہلے یہ مین کاؤنٹر لے جا کر ادائیگی کریں۔",
  "Taken": "لیا گیا",
  "Taken automatically every 12 hours; the last 14 are kept": "ہر بارہ گھنٹے بعد خودبخود؛ آخری چودہ محفوظ رہتے ہیں",
  "Taken off the store automatically when the result is saved, so consumption is recorded without anyone issuing by hand.": "نتیجہ محفوظ ہوتے ہی اسٹور سے خودبخود کم ہو جاتا ہے، اس لیے استعمال ہاتھ سے اندراج کے بغیر درج ہو جاتا ہے۔",
  "Takes samples, enters results, issues reports": "نمونے لیتا ہے، نتائج درج کرتا ہے، رپورٹ جاری کرتا ہے",
  "Tax": "ٹیکس",
  "Tax rate (%)": "ٹیکس کی شرح (٪)",
  "Tells the patient what to do next": "مریض کو اگلا قدم بتاتا ہے",
  "Temperature": "درجہ حرارت",
  "Test": "ٹیسٹ",
  "Test only": "صرف ٹیسٹ",
  "Test setup": "ٹیسٹ کی ترتیب",
  "Tests": "ٹیسٹ",
  "Tests and scans": "ٹیسٹ اور اسکین",
  "Tests only — lab or x-ray": "صرف ٹیسٹ — لیب یا ایکسرے",
  "Tests without a consultation": "بغیر ڈاکٹر کے ٹیسٹ",
  "Tests, scans and procedures": "ٹیسٹ، اسکین اور طریقہ ہائے کار",
  "The MRN cannot be changed. Every visit, prescription and chit points at it.": "ایم آر این تبدیل نہیں ہو سکتا۔ ہر دورہ، نسخہ اور پرچی اسی سے جڑی ہے۔",
  "The OPD counter takes the patient's details first, then sends them in. They appear here.": "او پی ڈی کاؤنٹر پہلے مریض کی تفصیل لیتا ہے، پھر بھیجتا ہے۔ وہ یہاں نظر آئیں گے۔",
  "The consultation itself. The counter still books appointments and takes the fee either way": "صرف معائنہ۔ کاؤنٹر بہرحال اپائنٹمنٹ بک کرتا اور فیس لیتا رہے گا",
  "The department can start once this is completed.": "یہ مکمل ہوتے ہی شعبہ کام شروع کر سکتا ہے۔",
  "The department will not start until this reads PAID.": "جب تک اس پر ادا شدہ نہ لکھا ہو شعبہ کام شروع نہیں کرے گا۔",
  "The first one is taken shortly after the server starts.": "پہلا بیک اپ سرور چلنے کے کچھ دیر بعد لیا جاتا ہے۔",
  "The laboratory takes no payments. A test appears here once it has been paid for at the main counter.": "لیبارٹری کوئی ادائیگی وصول نہیں کرتی۔ ٹیسٹ یہاں تب آتا ہے جب مین کاؤنٹر پر اس کی ادائیگی ہو چکی ہو۔",
  "The main counter and administration are always on — without them nobody can register a patient or sign in.": "مین کاؤنٹر اور انتظامیہ ہمیشہ فعال رہتے ہیں — اُن کے بغیر نہ مریض رجسٹر ہو سکتا ہے نہ کوئی داخل ہو سکتا ہے۔",
  "The most reliable way to find them again": "انہیں دوبارہ تلاش کرنے کا سب سے بھروسہ مند ذریعہ",
  "The old one stops working immediately and any open session is ended.": "پرانا فوراً بند ہو جائے گا اور کھلا سیشن ختم ہو جائے گا۔",
  "The patient is live on the floor straight away. The consultation fee appears at the main counter to be collected when someone can get to the window.": "مریض فوراً فلور پر آ جاتا ہے۔ ڈاکٹر کی فیس مین کاؤنٹر پر ظاہر ہو گی، جو کوئی کھڑکی تک پہنچنے پر ادا کر دے۔",
  "The patient is now in the queue. Send them to the OPD counter.": "مریض اب قطار میں ہے۔ انہیں او پی ڈی کاؤنٹر بھیجیں۔",
  "The patient joins the queue when this is completed.": "یہ مکمل ہوتے ہی مریض قطار میں شامل ہو جائے گا۔",
  "The person who collected it": "جس نے وصول کی",
  "The report is ready to print.": "رپورٹ چھپنے کے لیے تیار ہے۔",
  "The stock is on the shelf.": "اسٹاک شیلف پر آ گیا ہے۔",
  "The store could not be updated for everything this test uses": "اس ٹیسٹ میں استعمال ہونے والی ہر شے کے لیے اسٹور اپ ڈیٹ نہیں ہو سکا",
  "The test itself is unaffected. Tell the store so a count can put it right.": "ٹیسٹ خود متاثر نہیں ہوا۔ اسٹور کو بتائیں تاکہ گنتی سے درست کر لیا جائے۔",
  "Their invoice number": "اُن کا انوائس نمبر",
  "These settings apply to this computer only.": "یہ ترتیبات صرف اسی کمپیوٹر پر لاگو ہوتی ہیں۔",
  "They earn": "اُن کی آمدنی",
  "They owe": "اُن کے ذمے",
  "They will appear in the doctor's Ready for you list straight away.": "وہ فوراً ڈاکٹر کی \\\"آپ کے لیے تیار\\\" فہرست میں آ جائیں گے۔",
  "They will be marked as with you, and reception will see them leave the queue.": "انہیں آپ کے پاس درج کر دیا جائے گا، اور استقبالیہ انہیں قطار سے نکلتا دیکھے گا۔",
  "They will be marked as with you, and the counters will see them leave the queue.": "انہیں آپ کے پاس درج کر دیا جائے گا، اور کاؤنٹر انہیں قطار سے نکلتا دیکھیں گے۔",
  "This chooses your starting screen. What you can actually do comes from your account.": "یہ صرف ابتدائی اسکرین چنتا ہے۔ اصل اختیارات آپ کے اکاؤنٹ سے طے ہوتے ہیں۔",
  "This covers": "یہ شامل کرتا ہے",
  "This department takes no payments. Work appears here once it has been paid for at the main counter.": "یہ شعبہ کوئی ادائیگی وصول نہیں کرتا۔ کام یہاں تب آتا ہے جب مین کاؤنٹر پر ادائیگی ہو چکی ہو۔",
  "This doctor": "یہ ڈاکٹر",
  "This expires — ask for an expiry date when receiving it": "اس کی میعاد ہوتی ہے — وصولی پر تاریخ پوچھی جائے",
  "This is an administrator. They keep full access regardless of what is ticked here.": "یہ منتظم ہے۔ یہاں جو بھی نشان لگا ہو، اِن کی مکمل رسائی برقرار رہے گی۔",
  "This month": "رواں ماہ",
  "This records who took it and when. Both print on the report.": "یہ درج کرتا ہے کہ کس نے اور کب لیا۔ دونوں رپورٹ پر چھپتے ہیں۔",
  "This records who took it and when. The report prints both.": "یہ درج کرتا ہے کہ کس نے اور کب لیا۔ رپورٹ پر دونوں چھپتے ہیں۔",
  "This removes": "یہ ہٹا دے گا",
  "This sets the order on the floor list, so put it in honestly.": "اس سے فلور کی ترتیب طے ہوتی ہے، اس لیے درست درج کریں۔",
  "This system already has patient records": "اس نظام میں پہلے سے مریضوں کا ریکارڈ موجود ہے",
  "This was a credit sale, so nothing comes out of the drawer.": "یہ ادھار فروخت تھی، اس لیے دراز سے کچھ نہیں نکلتا۔",
  "This was sold on account, so the refund goes to their ledger rather than out of the drawer.": "یہ ادھار پر فروخت ہوا تھا، اس لیے رقم دراز سے نہیں بلکہ اُن کے کھاتے میں جمع ہو گی۔",
  "Through the day": "دن بھر",
  "Time": "وقت",
  "To": "تا",
  "Today": "آج",
  "Today's queue": "آج کی قطار",
  "Token": "ٹوکن",
  "Token number": "ٹوکن نمبر",
  "Token, name, MRN or phone": "ٹوکن، نام، ایم آر این یا فون",
  "Top": "سرفہرست",
  "Total": "کل",
  "Total earned": "کل آمدنی",
  "Trade": "ٹریڈ",
  "Trade rate": "ٹریڈ ریٹ",
  "Triage": "درجہ بندی",
  "Turn off if you use pre-printed paper": "پہلے سے چھپے کاغذ پر بند رکھیں",
  "Two is usual where one goes in the file": "جہاں ایک کاپی فائل میں جاتی ہو وہاں دو معمول ہے",
  "Type": "قسم",
  "Type the name here — if they have been before, pick them from the list": "نام یہاں لکھیں — اگر پہلے آ چکے ہوں تو فہرست سے منتخب کریں",
  "Ultrasound": "الٹراساؤنڈ",
  "Unit": "اکائی",
  "Units": "یونٹ",
  "Units per pack": "فی پیک یونٹ",
  "Units per purchase pack": "فی خریداری پیک اکائیاں",
  "Unlink": "تعلق ختم کریں",
  "Unpaid": "واجب الادا",
  "Unsaved changes": "غیر محفوظ تبدیلیاں",
  "Unticked means refused, whatever the role would normally allow": "نشان نہ ہونے کا مطلب انکار ہے، چاہے ذمہ داری عام طور پر اجازت دیتی ہو",
  "Update details": "تفصیل تازہ کریں",
  "Upper": "اوپری",
  "Urgent": "فوری",
  "Urine": "پیشاب",
  "Use this": "یہی منتخب کریں",
  "Use this record": "یہی ریکارڈ استعمال کریں",
  "Used by department": "شعبے کے حساب سے استعمال",
  "Used to group staff and to label visits": "عملے کی درجہ بندی اور دوروں کے لیبل کے لیے",
  "Username": "صارف نام",
  "Value": "مالیت",
  "Value at risk": "خطرے میں مالیت",
  "Value on the shelf": "شیلف پر مالیت",
  "Verify": "تصدیق کریں",
  "View": "ویو",
  "View &amp; print": "دیکھیں اور پرنٹ کریں",
  "Viral fever": "وائرل بخار",
  "Visits": "دورے",
  "Vitals not taken": "ابتدائی معائنہ نہیں ہوا",
  "Waiting": "منتظر",
  "Waiting for you": "آپ کے منتظر",
  "Waiting now": "اس وقت منتظر",
  "Waiting outside the doctor's door": "ڈاکٹر کے دروازے پر منتظر",
  "Walk-in": "بغیر وقت",
  "Walk-in admissions and bedside medicines": "براہِ راست داخلے اور بستر پر دی گئی ادویات",
  "Warn when the shelf drops to this": "اس حد پر پہنچنے پر خبردار کریں",
  "We owe": "ہمارے ذمے",
  "Weight": "وزن",
  "What": "کیا",
  "What a doctor can order, what it costs, and the default cut the ordering doctor gets": "ڈاکٹر کیا تجویز کر سکتا ہے، اس کی قیمت، اور تجویز کرنے والے کا طے شدہ حصہ",
  "What are they here for?": "وہ کس لیے آئے ہیں؟",
  "What each one got through": "ہر شعبے نے کتنا استعمال کیا",
  "What for": "کس لیے",
  "What happened": "کیا ہوا",
  "What happened to them": "مریض کے ساتھ کیا ہوا",
  "What it uses up": "کیا استعمال ہوتا ہے",
  "What should be in the drawer at handover": "حوالگی کے وقت دراز میں کیا ہونا چاہیے",
  "What should physically be in the drawer at close": "بندش کے وقت دراز میں عملاً کیا ہونا چاہیے",
  "What the customer pays, per unit": "گاہک فی اکائی کیا ادا کرتا ہے",
  "What the patient pays": "مریض کیا ادا کرتا ہے",
  "What they have come in for, in their words": "وہ کس لیے آئے، اُنہی کے الفاظ میں",
  "What they have come in with": "وہ کیا شکایت لے کر آئے ہیں",
  "What this test reports": "یہ ٹیسٹ کیا رپورٹ کرتا ہے",
  "What you pay, per unit": "آپ فی اکائی کیا ادا کرتے ہیں",
  "When": "کب",
  "When to take it": "کب لینی ہے",
  "Where are you working?": "آپ کہاں کام کر رہے ہیں؟",
  "Where it lives": "کہاں رکھی جاتی ہے",
  "Which printer is used comes from Windows, not from here — a web page is not allowed to choose a device. Set the roll printer as the default printer on this PC and every slip will go to it.": "کون سا پرنٹر استعمال ہو گا یہ ونڈوز طے کرتا ہے، یہاں سے نہیں — ویب صفحہ ڈیوائس منتخب نہیں کر سکتا۔ اس کمپیوٹر پر رول پرنٹر کو ڈیفالٹ بنا دیں، ہر پرچی اسی پر جائے گی۔",
  "Why": "وجہ",
  "Will be registered as": "اس نام سے رجسٹر ہو گا",
  "Windows: Settings, Bluetooth and devices, Printers and scanners, pick the printer, Set as default. Turn off \"Let Windows manage my default printer\" first.": "ونڈوز: سیٹنگز، بلوٹوتھ اینڈ ڈیوائسز، پرنٹرز اینڈ اسکینرز، پرنٹر منتخب کریں، سیٹ ایز ڈیفالٹ۔ پہلے \"Let Windows manage my default printer\" بند کریں۔",
  "With": "ہمراہ",
  "With the doctor": "ڈاکٹر کے پاس",
  "Work list": "کام کی فہرست",
  "Written by hand — not linked to a shelf item": "ہاتھ سے لکھی گئی — اسٹاک سے منسلک نہیں",
  "Written off": "ضائع شدہ",
  "Written to the server's": "سرور کے اس فولڈر میں محفوظ",
  "Wrong medicine, patient did not need it": "غلط دوا، مریض کو ضرورت نہیں تھی",
  "X-Ray Chest": "ایکسرے سینہ",
  "X-ray": "ایکسرے",
  "X-ray and imaging — its own work list": "ایکسرے اور امیجنگ — اپنی الگ فہرست",
  "X-ray, ultrasound and imaging": "ایکسرے، الٹراساؤنڈ اور امیجنگ",
  "X-ray, ultrasound and imaging reports": "ایکسرے، الٹراساؤنڈ اور امیجنگ رپورٹیں",
  "Yes, confirm": "جی ہاں، تصدیق کریں",
  "Yes, see this patient": "جی ہاں، یہ مریض دیکھیں",
  "Yes, send them in": "جی ہاں، بھیج دیں",
  "Yesterday": "گزشتہ کل",
  "Your name": "آپ کا نام",
  "Your own code": "آپ کا اپنا کوڈ",
  "Your own reference, if you use one": "آپ کا اپنا حوالہ، اگر استعمال کرتے ہوں",
  "Your share is a percentage of this": "آپ کا حصہ اسی کا فیصد ہے",
  "accounts": "کھاتے",
  "adjust": "درستی",
  "admin": "منتظم",
  "admin / admin-demo-1": "admin / admin-demo-1",
  "against": "کے خلاف",
  "already returned": "پہلے واپس ہو چکی",
  "archived": "محفوظ شدہ",
  "at the OPD counter": "او پی ڈی کاؤنٹر پر",
  "at the main counter": "مین کاؤنٹر پر",
  "available": "دستیاب",
  "avg": "اوسط",
  "back on the shelf": "دوبارہ شیلف پر",
  "backups": "backups",
  "bank": "بینک",
  "bonus packs": "بونس پیک",
  "by": "بلحاظ",
  "can do": "کر سکتے ہیں",
  "cancelled": "منسوخ",
  "card": "کارڈ",
  "cash": "نقد",
  "cheque": "چیک",
  "cleaning": "صفائی",
  "clear": "صاف",
  "collected": "نمونہ لیا گیا",
  "completed": "مکمل",
  "consumable": "استعمالی",
  "controlled": "ممنوعہ",
  "costs and sells for. The price of a whole pack is worked out from the pack size, so the two can never disagree.": "کی خرید اور فروخت کی قیمت کیا ہے۔ پورے پیک کی قیمت پیک سائز سے خودبخود نکل آتی ہے، اس لیے دونوں میں فرق نہیں ہو سکتا۔",
  "counter": "کاؤنٹر",
  "credit": "ادھار",
  "critical": "تشویشناک",
  "days": "دن",
  "default": "طے شدہ",
  "dispensed": "دی گئی",
  "doctor": "ڈاکٹر",
  "done": "مکمل",
  "dr.yasir / 1234": "dr.yasir / 1234",
  "easypaisa": "ایزی پیسہ",
  "erases everything": "سب کچھ مٹا دیتا ہے",
  "exp": "میعاد",
  "expired": "میعاد ختم",
  "expires": "میعاد",
  "fees": "فیس",
  "female": "عورت",
  "filled": "بھرے",
  "from batch": "بیچ سے",
  "from the system for good.": "نظام سے ہمیشہ کے لیے۔",
  "g": "شیڈول جی",
  "has already expired and is still on the shelf": "کی میعاد ختم ہو چکی ہے اور شیلف پر موجود ہے",
  "hidden": "پوشیدہ",
  "high": "زیادہ",
  "hr": "گھنٹے",
  "in stock": "اسٹاک میں",
  "in_progress": "جاری",
  "instrument": "آلہ",
  "issue": "جاری",
  "jazzcash": "جاز کیش",
  "kg": "کلوگرام",
  "lab": "لیبارٹری",
  "lab report": "لیب رپورٹ",
  "last seen": "آخری بار",
  "left": "باقی",
  "linen": "بستر پوش",
  "lines": "سطریں",
  "locked": "مقفل",
  "low": "کم",
  "main_counter": "مین کاؤنٹر",
  "male": "مرد",
  "mark paid": "ادا شدہ لکھیں",
  "medicines not collected from the pharmacy": "ادویات فارمیسی سے نہیں لی گئیں",
  "medicines not yet collected": "ادویات ابھی نہیں لی گئیں",
  "mg/dL": "ملی گرام/ڈی ایل",
  "min": "منٹ",
  "missing": "کم",
  "more than expected": "توقع سے زیادہ",
  "n/a": "لاگو نہیں",
  "new": "نیا",
  "no expiry": "میعاد نہیں",
  "no stock": "اسٹاک نہیں",
  "not collected": "نہیں لی گئی",
  "not in pharmacy": "فارمیسی میں نہیں",
  "not paid": "ادائیگی نہیں ہوئی",
  "of": "کا",
  "of revenue": "آمدنی کا",
  "on credit": "ادھار پر",
  "on hand": "موجود",
  "on the bench": "زیرِ عمل",
  "on the shelf": "شیلف پر",
  "only": "صرف",
  "ordered": "آرڈر شدہ",
  "otc": "عام دستیاب",
  "other": "دیگر",
  "out of stock": "اسٹاک ختم",
  "pack": "پیک",
  "paid": "ادا شدہ",
  "partial": "جزوی",
  "patients": "مریض",
  "pending": "زیرِ التوا",
  "people already registered look like this person": "پہلے سے رجسٹرڈ افراد اِن سے ملتے ہیں",
  "pharmacist": "فارماسسٹ",
  "pharmacy / 1234": "pharmacy / 1234",
  "piece, roll, box, pair": "عدد، رول، ڈبہ، جوڑا",
  "ppe": "حفاظتی سامان",
  "preview is exact": "پیش نظارہ بالکل ویسا ہی ہے",
  "procedure": "طریقہ کار",
  "radiology": "ریڈیالوجی",
  "ready": "تیار",
  "receive": "وصول",
  "reception / 1234": "main-counter / 1234",
  "receptionist": "او پی ڈی کاؤنٹر",
  "refrigerated": "فریج میں",
  "refunded": "واپس کی گئی",
  "registered": "رجسٹرڈ",
  "reorder at": "دوبارہ آرڈر کی حد",
  "reported": "رپورٹ شدہ",
  "resulted": "رپورٹ شدہ",
  "retired": "غیر فعال",
  "return": "واپسی",
  "returned": "واپس ہوا",
  "rows": "سطریں",
  "sample not taken": "نمونہ نہیں لیا گیا",
  "sched G": "شیڈول جی",
  "schedule G": "شیڈول جی",
  "selected": "منتخب شدہ",
  "sent in": "بھیج دیا گیا",
  "shown below but locked. Take the sample first, then come back; anything you type here is kept.": "نیچے دکھائے گئے ہیں مگر مقفل ہیں۔ پہلے نمونہ لیں، پھر واپس آئیں؛ جو کچھ آپ یہاں لکھیں گے محفوظ رہے گا۔",
  "standard": "عام",
  "stationery": "اسٹیشنری",
  "still at the main counter": "ابھی مین کاؤنٹر پر",
  "strip": "پتہ",
  "suppliers": "سپلائر",
  "tablet": "گولی",
  "test": "ٹیسٹ",
  "tests": "ٹیسٹ",
  "tests on this visit have no sample yet": "ٹیسٹوں کا نمونہ ابھی نہیں لیا گیا",
  "to": "تا",
  "to collect": "لینا باقی",
  "to enable": "فعال کرنے کے لیے",
  "token": "ٹوکن",
  "unit": "اکائی",
  "units": "اکائیاں",
  "unpaid": "واجب الادا",
  "up to": "زیادہ سے زیادہ",
  "urgent": "فوری",
  "verified": "تصدیق شدہ",
  "waiting": "منتظر",
  "waiting to pay": "ادائیگی کا منتظر",
  "waste": "ضائع",
  "with doctor": "ڈاکٹر کے پاس",
  "with the counters, not yet sent in": "کاؤنٹر پر ہیں، ابھی نہیں بھیجے گئے",
  "with you": "آپ کے پاس",
  "written off": "ضائع شدہ",
  "written off, not resaleable": "ضائع شدہ، دوبارہ فروخت نہیں",
}

/**
 * The floating control.
 *
 * Bottom right, above everything, out of the way of the tables and the till.
 * Deliberately not buried in a settings screen: someone squinting at a bright
 * screen at 9pm should be one click from fixing it, not five.
 */
export function AppearanceToggle() {
  const { theme, toggleTheme, setTheme, lang, setLang, t: tr } = usePrefs()
  const [open, setOpen] = useState<'none' | 'theme' | 'lang'>('none')

  return (
    <div className="no-print fixed bottom-5 right-5 z-50 flex flex-col items-end gap-2">
      {open === 'theme' && (
        <div className="panel w-60 p-1.5 shadow-pop">
          <p className="px-2 pb-1 pt-0.5 text-2xs uppercase tracking-wide text-muted">Appearance</p>
          {THEMES.map((th) => (
            <button key={th.id} onClick={() => { setTheme(th.id); setOpen('none') }}
              className={`flex w-full items-center gap-2.5 rounded-xl px-2.5 py-2 text-left ${
                theme === th.id ? 'bg-primary/10' : 'hover:bg-raised'}`}>
              <span className="flex shrink-0 overflow-hidden rounded-md border border-line">
                {th.swatch.map((c) => (
                  <span key={c} className="h-6 w-2.5" style={{ background: c }} />
                ))}
              </span>
              <span className="min-w-0 flex-1">
                <span className={`block text-sm ${
                  theme === th.id ? 'font-medium text-primary' : 'text-body'}`}>{th.label}</span>
                <span className="block text-2xs text-muted">{th.note}</span>
              </span>
              {theme === th.id && <span className="text-primary">&#10003;</span>}
            </button>
          ))}
        </div>
      )}

      {open === 'lang' && (
        <div className="panel w-52 p-1.5 shadow-pop">
          <button onClick={() => { setLang('en'); setOpen('none') }}
            className={`flex w-full items-center justify-between rounded-xl px-3 py-2 text-sm ${
              lang === 'en' ? 'bg-primary/10 font-medium text-primary' : 'text-body hover:bg-raised'}`}>
            English <span className="text-2xs opacity-60">EN</span>
          </button>
          <button onClick={() => { setLang('ur'); setOpen('none') }}
            className={`flex w-full items-center justify-between rounded-xl px-3 py-2 ${
              lang === 'ur' ? 'bg-primary/10 font-medium text-primary' : 'text-body hover:bg-raised'}`}>
            <span className="font-urdu text-base">&#1575;&#1585;&#1583;&#1608;</span>
            <span className="text-2xs opacity-60">UR</span>
          </button>
        </div>
      )}

      <div className="flex items-center gap-2">
        <button onClick={() => setOpen((o) => (o === 'lang' ? 'none' : 'lang'))}
          aria-label={tr('Language')}
          className="flex h-11 items-center rounded-full border-2 border-line bg-card px-4 text-sm
                     font-medium text-body shadow-pop transition-colors hover:border-primary">
          {lang === 'en' ? 'EN' : <span className="font-urdu">&#1575;&#1585;&#1583;&#1608;</span>}
        </button>

        <button onClick={() => setOpen((o) => (o === 'theme' ? 'none' : 'theme'))}
          aria-label="Appearance"
          className="flex h-11 w-11 items-center justify-center rounded-full border-2 border-line
                     bg-card text-body shadow-pop transition-colors hover:border-primary">
          <Palette />
        </button>

        <button onClick={toggleTheme}
          aria-label={theme === 'dark' ? t('Light mode') : t('Dark mode')}
          title={theme === 'dark' ? t('Light mode') : t('Dark mode')}
          className="flex h-11 w-11 items-center justify-center rounded-full bg-brand text-white
                     shadow-pop transition-transform hover:scale-105 active:scale-95">
          {theme === 'dark' ? <Sun /> : <Moon />}
        </button>
      </div>
    </div>
  )
}

function Palette() {
  return (
    <svg viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="2"
      strokeLinecap="round" strokeLinejoin="round">
      <circle cx="13.5" cy="6.5" r=".5" fill="currentColor" />
      <circle cx="17.5" cy="10.5" r=".5" fill="currentColor" />
      <circle cx="8.5" cy="7.5" r=".5" fill="currentColor" />
      <circle cx="6.5" cy="12.5" r=".5" fill="currentColor" />
      <path d="M12 2a10 10 0 0 0 0 20 2 2 0 0 0 2-2 2 2 0 0 1 2-2h2a4 4 0 0 0 4-4 10 10 0 0 0-10-10Z" />
    </svg>
  )
}

function Moon() {
  return (
    <svg viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="2"
      strokeLinecap="round" strokeLinejoin="round">
      <path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8Z" />
    </svg>
  )
}

function Sun() {
  return (
    <svg viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="2"
      strokeLinecap="round" strokeLinejoin="round">
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4" />
    </svg>
  )
}
